### ISSUE TITLE
Flowrouter.go() vs. {...}.redirect()

### ISSUE THREAD

**Issue by Streemo** [meteorhacks/flow-router#100]
I noticed something when trying the former solution.

`FlowRouter.go(pathA)` will not run `pathA`'s middleware if I'm already at `pathA`. However, if I use `Flowrouter.redirect(pathA)`, the route will be run fully with middleware (like expected) regardless of what path I'm currently at.

Is this intended behavior? 

Since FR is non-reactive by design, a common pattern is to rerun a route in light of new information. This seems to go against the design of FR (because that's pretty much what Iron Router does) so I am wondering whether or not its a better idea to render a different template instead of rerouting.

USE CASE: I have `loginMiddleware` which is very basic and renders a `loginTemplate` if the user isn't logged in. Once the user signs in from this view, I want the route to be re-run in light of the fact that she is now signed in. In the logging in callback function, I `FlowRouter.redirect(currentPath)` and all is well. Instead I'm thinking it might be a better idea to `FlowLayout.render('layout',ifLoggedInTemplates)` in the callback. Thoughts?

Another solution is to implement a separate sign-in route which is hit in the loginMiddleware if not signed in, and keep n=1 route history, and then just redirect back to the previous page after the user signs in.

**Comment by arunoda** [comment]
We are doing some checks on FlowRouter.go to stop running route if called multiple times. Which means routes are idempotent. I like that idea. We need to do it for .redirect as well.

But, I'm still quite not sure this is the right way or not. May be I need to trust my gut feeling.

Handling login related stuff is pretty messy now. We need to find a way for that. I'll work on that, once I fixed major bugs.

**Comment by arunoda** [comment]
I think I'll keep both .redirect()  and .go() idempotent. Then we can have .reload() api.

**Comment by Streemo** [comment]
@arunoda I think the idempotency is fine, but if you make both .go() and
.redirect() this way then I agree that there should be a .reload()
functionality which is not idempotent.

+1 for that.

Question, what is the difference between redirect and go (assuming both are
idempotent)? It seems I can use them interchangeably (minus the fact that
one of them currently is not idempotent)

**Comment by arunoda** [comment]
FlowRouter.redirect() can be used inside middlewares to redirect the route. Then it gives us clean history. see: https://visionmedia.github.io/page.js/

But, we need to complete this API a bit and add more docs.

**Comment by Streemo** [comment]
I see, that clears things up. Thanks arunoda.

**Comment by Streemo** [comment]
@arunoda currently I (and I'm sure others) are relying on at least one of
these operations being repeatable (non-idempotent). If you decide to turn
both redirect and go into idempotent operations, it would be much
appreciated if first the reload() api is determined.

Thanks!

**Comment by arunoda** [comment]
I'm closing this favour of the reload API.

**Comment by niklasp** [comment]
can you share your loginMiddleware
