### ISSUE TITLE
Get the path definition by name to simulate ironRouter's pathFor

### ISSUE THREAD

**Issue by mbabauer** [meteorhacks/flow-router#102]
I am trying to write a global helper to act like the `pathFor` found in Iron Router.  Basically, I want to be able to pass in the name of the route as the first argument, and a variable bunch of named and un-named parameters, pull them out, then build the params to pass into `FlowRouter.path()`.

Here is what I have so far:
```javascript
Template.registerHelper('pathFor', function(pathOrName) {
  var params;
  _.each(arguments, function(arg, idx, arguments) {
    if (idx !== 0) {
      if (arg instanceof Spacebars.kw) {
        // pull out named pairs from the hash here and push them into the params
      } else {
        // This is where I am stuck!
      }
    }
  });
  
  return FlowRouter.path(pathOrName, params);
});
```

Where I am stuck is that I need to get the URL parts from the path, namely the :xxx parts, so I can properly "name" them as I push them into the params var, but I am not sure how to do this.  Any suggestions?

**Comment by miri-am** [comment]
Do you know this package: https://github.com/arillo/meteor-flow-router-helpers/

There is the implementation for pathFor: https://github.com/arillo/meteor-flow-router-helpers/blob/master/client/helpers.coffee

**Comment by arunoda** [comment]
Flow Router won't have such helpers and above package do that.
