### ISSUE TITLE
Flow-Router support in zimme:active-route

### ISSUE THREAD

**Issue by zimme** [meteorhacks/flow-router#108]
Just wanted to tell you guys that I've added support for `meteorhacks:flow-router` in version 2.0.0 of `zimme:iron-router-active` which I have renamed `zimme:active-route`.

Feel free to close issue.

Great work on this router. I've gotta play around with it a bit more when I have the time. :+1:

**Comment by arunoda** [comment]
Awesome ++++

**Comment by zimme** [comment]
Will move the package out of alpha/beta this weekend most likely
