### ISSUE TITLE
Uncaught SecurityError upon executing `replaceState`

### ISSUE THREAD

**Issue by rralian** [meteorhacks/flow-router#118]
I'm getting a strange error when using flow-router with velocity (mike:mocha). The app runs fine, but I get a security error in the browser console when the velocity tests run (no errors in the terminal, and the app still seems to run fine):
```
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'http:/?mocha=true&lastModified=1432278510287' cannot be created in a document with origin 'http://localhost:51251'.
```
I get this despite a very minimal amount of code. I can remove all routes and extraneous collections and still get the error. It seems like a package conflict. Here are my current packages.
```
meteor-platform
insecure
reactjs:react
less
meteorhacks:flow-router
ian:accounts-ui-bootstrap-3
twbs:bootstrap
accounts-password
accounts-facebook
mike:mocha
```
I'd appreciate any suggestions/help to address this.

**Comment by rralian** [comment]
A little more info, I confirmed that I get this same error with a stock install... can recreate with:
```bash
$ meteor create flow-test
$ cd flow-test
$ meteor add meteorhacks:flow-router
$ meteor add mike:mocha
$ meteor
```

---------------------
Then open the page and open the inspector (tested in chrome and firefox, issues appear in both spots).
![inspector error](https://cloudup.com/clDJymX_5GS+)

------------------------
The error appears in line 531 of the flow-router package file (specifically with a page.js method).
![page.js error](https://cloudup.com/cAsRmBz5_zN+)

----------------------------------------
And here are all my versions:
```bsh
➜  flow-test  meteor list
autopublish              1.0.3  Publish the entire database to all clients
insecure                 1.0.3  Allow all database writes by default
meteor-platform          1.2.2  Include a standard set of Meteor packages in your app
meteorhacks:flow-router  1.7.1  Carefully Designed Client Side Router for Meteor
mike:mocha               0.5.4  Run mocha tests in the browser
```

**Comment by rralian** [comment]
One more bit of info, I've tested `flow-router` versions `1.6.0`, `1.7.0`, and `1.7.1` and found this same error in each version. I swear (ok, like 80% sure) this wasn't happening a week ago (came back to the project and started seeing this), so I'm not sure what happened. Doesn't look like mocha-web has been updated recently either.

**Comment by arunoda** [comment]
I suspect this is due to mocha web and it's trying to use the meteor app on
a different port. I'm not familiar with mocha web, but I'm think it's doing
something browser don't like to do.

**Comment by arunoda** [comment]
I'm going to close this issue since this is not something we can control.
