### ISSUE TITLE
What difference global subscriptions vs subscriptions on router?

### ISSUE THREAD

**Issue by yuomtheara** [meteorhacks/flow-router#119]
I don't understand to declare subscriptions for global and subscriptions on router?
What difference, please explan me??
```js
FlowRouter.route('/blog/:postId', {
    subscriptions: function(params, queryParams) {
        this.register('myPost', Meteor.subscribe('blogPost', params.postId));
    }
});

FlowRouter.subsReady("myPost")
--------------------
// in client/lib/subscriptions.js
Meteor.subscribe('blogPost', params.postId)
```

**Comment by arunoda** [comment]
If you register it globally, it  will run on all the routes. If not subscription only runs for the given route. When you change the route, route specific subscriptions will unsubscribe.

Do you need more clarifications?

**Comment by yuomtheara** [comment]
Very thank, for your explain. So it mean that we can use all of subscriptions (on router) in template helper, event .... What difference if I use `subscriptions ` on template helper or events when we need it.

**Comment by arunoda** [comment]
I think you are referring to subscription data, it thats, yes it is.

**Comment by yuomtheara** [comment]
but sometime I get `undefined`.

**Comment by arunoda** [comment]
I need some sample code. It's hard to tell like this.

**Comment by yuomtheara** [comment]
I used to use subscriptions on template events
```js
Template.myTemplate.events(
   'click #id': function(){
      Meteor.subscribe('blogPost');
      var data = BlogPost.find();

      // doing with data

         return ..........;
      }
  }
)
```
but get `undefined` of data

**Comment by yuomtheara** [comment]
OK If I user it on router, so I need to check subsReady() like:
```js
Template.myTemplate.events(
   'click #id': function(){
      if(FlowRouter.subsReady("myPost")){
         // doing with subscriptions
         return ..........;
      }
  }
)
```

**Comment by arunoda** [comment]
`BlogPost.find()` never won't be undefined.  In an helper you can subsReady. But for an event, you need to use subsReady() inside a `Tracker.autorun()`. Otherwise, it won't run again.

~~~js
Template.myTemplate.events(
   'click #id': function(){
      Tracker.autorun(function(c) {
        if(FlowRouter.subsReady("myPost")){
           // do something with the data
           c.stop();
        }
      });
  }
)
~~~

We need a different feature here. To specify a callback when the subsReady. I'll add new feature request.

**Comment by arunoda** [comment]
I added a new feature request here: #120

**Comment by arunoda** [comment]
I'm closing this issue for now. For this feature, lets talk on #120 
If this is not what you are looking for, open the issue again.
