### ISSUE TITLE
Accept callback for `subsReady`

### ISSUE THREAD

**Issue by arunoda** [meteorhacks/flow-router#120]
This is very useful for events where we don't have to run a autorun. 
See this issue: https://github.com/meteorhacks/flow-router/issues/119#issuecomment-104836746

Here's the suggest API:

~~~js
Template.myTemplate.events(
   'click #id': function(){
      FlowRouter.subsReady("myPost", function() {
         // do something
      });
  }
)
~~~

**Comment by delgermurun** [comment]
@arunoda do we need `autorun` here?

how about this?

```js
Template.myTemplate.events(
   'click #id': function(){
      FlowRouter.subsReady("myPost", function() {
        // do something
      });
  }
)
```

**Comment by arunoda** [comment]
Ah nope. We don't need it :)
I'll update it.
