### ISSUE TITLE
notFound for grouped routes?

### ISSUE THREAD

**Issue by rclai** [meteorhacks/flow-router#123]
https://github.com/meteorhacks/flow-router#not-found-routes

```js
teamRoutes = FlowRouter.group({
  prefix: '/teams/:team'
});

teamRoutes.notFound = {
  action: function () {
    // ...
  }
};
```

Only this works:

```js
FlowRouter.notFound = {
  action: function () {
    // ...
  }
};
```

**Comment by arunoda** [comment]
I need to think twice for this. Quite not sure how to build the logic for
this.

**Comment by arunoda** [comment]
@delgermurun do you have any idea how to support this feature?

**Comment by delgermurun** [comment]
First of all do we really need it :)? @rclai what is your use case?

Since all path definition doesn't match, it is hard to know which `notFound` to call.

@rclai do we call `teamRoutes`'s `notFound` when path is something like `/teams/foo/not-found`?

**Comment by rclai** [comment]
Oh yeah, that would be tough. I suppose that we could do the logic in the global `.notFound()` action.

**Comment by arunoda** [comment]
Yes. You can call  `FlowRouter.current()` and access the path.
See: https://github.com/meteorhacks/flow-router#flowroutercurrent

**Comment by arunoda** [comment]
If you found a way to implement your logic, hope we can close this issue.
It's not a good time for this feature. 
We got bunch of keys features to be implemented.

**Comment by robertpitt** [comment]
Is this a good time to re-address this issue, as I have just come into the same problems.

## My use-case.

I am developing a project that separates the front-end and back-end areas into packages, both of these packages use a base package `atomic:router`, which set's a default 404 handler.

Needing to keep the admin package 100% independent is broken by a grouped route not being as fully featured as the base router controller.

Regards.
