### ISSUE TITLE
"watchPathChange for every route change" test fails

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-router#125]
```
C: watchPathChange for every route change
- fail — assert_equal - expected [null,"one","two","three"] - actual [null,"one"] - not
```

**Comment by arunoda** [comment]
When this happens? I couldn't reproduce it.

**Comment by delgermurun** [comment]
I created fresh new meteor app. Added `meteorhacks:flow-router`.

`meteor test-packages meteorhacks:flow-router` run this command. `Passed 59 of 60`

**Comment by arunoda** [comment]
Hmm. I normally test by visiting to the flow router project and apply:

meteor test-packages ./

Then it worked. I will try like this too.

**Comment by delgermurun** [comment]
`meteor test-packages ./` by this command, all tests passed.

**Comment by delgermurun** [comment]
I added
```js
FlowRouter.route('/', {
  subscriptions: function() {
    console.log('subscribe');
    this.register('posts', Meteor.subscribe('posts'));
  }
});
```

this one route to meteor app.

**Comment by delgermurun** [comment]
Seems like working fine now. Closing
