### ISSUE TITLE
FlowRouter.getRouteName doesn't exist?

### ISSUE THREAD

**Issue by mattkrick** [meteorhacks/flow-router#126]
Couldn't find the `getRouteName` method, not sure if this is an error or just needs to be changed in the docs to (presumably) `FlowRouter.reactiveCurrent().route.name`

**Comment by arunoda** [comment]
May be you are using an older version. Check your `.meteor/versions` file to see you are using the latest version which is `1.9.0`

**Comment by mattkrick** [comment]
That did it. It installed 1.5.0 because of some constraint with coffeescript (forgot I'm running on devel branch). I manually updated the version to 1.9.0. Cheers
