### ISSUE TITLE
Question: are subscriptions idempotent across routes?

### ISSUE THREAD

**Issue by jonjamz** [meteorhacks/flow-router#13]
If I navigate from one route to another and both use the same subscription, is the subscription re-run?

**Comment by arunoda** [comment]
Yes. That behaviour is very similar to Iron Router. You can avoid that also using the subs-manager.

**Comment by jonjamz** [comment]
What about this?

```javascript
Route.prototype.subscribe = function(name, sub, options) {
  if (!this._subsMap[name]) {
    this._subsMap[name] = sub;
  };
};
```

**Comment by arunoda** [comment]
Why do you suggest that?
we are running all these subs inside a autorun computation. So all the previous subscriptions will get destroyed in the new route.
We've no intention to change this.

If we need some additional handling, I suggest to use subs-manager or do it manually. 

If you have any specific use case, let's see what we can do about it.

**Comment by arunoda** [comment]
May be @mnmtanish help me out also. We wrote this router.

**Comment by jonjamz** [comment]
Actually since you're running the subs in autorun, I think Meteor won't re-run a sub with the same arguments anyway, right?

**Comment by arunoda** [comment]
Yes. it simply give us the ready() of the previous one.
That's what subs-manager does also behind the scene.

**Comment by jonjamz** [comment]
:+1: 

By the way, thanks for writing this.

**Comment by arunoda** [comment]
Sorry for not having docs. We're finalizing some features and we can release all these with flow at the end of this month.

**Comment by jonjamz** [comment]
I can help if you want!

**Comment by arunoda** [comment]
That's awesome. Let me work on the docs and we can then think about fixes.
I wan this router to be minimalistic as possible.

**Comment by jonjamz** [comment]
Awesome. I love the minimal approach.
