### ISSUE TITLE
Ugly named route group '/' urls

### ISSUE THREAD

**Issue by VladShcherbin** [meteorhacks/flow-router#130]
Example: user group routes (named)
```js
var usersGroup = FlowRouter.group({
  prefix: '/admin/users'
});

usersGroup.route('/', {
  name: 'admin.users.index',
  action: function () {
    FlowLayout.render('adminBasicLayout', {main: 'adminUsersIndex'});
  }
});

usersGroup.route('/create', {
  name: 'admin.users.create',
  action: function () {
    FlowLayout.render('adminBasicLayout', {main: 'adminUsersCreate'})
  }
});
```

Now we want a link for a named route
```js
FlowRouter.path('admin.users.index');
```

The route for the **/** action will be:
```
http://localhost:3000/admin/users/
```

The last **/** is very ugly, can we remove it?

**Comment by arunoda** [comment]
Why not we can remove it. I will mark this as a bug. So, we can work on
this.

**Comment by delgermurun** [comment]
@arunoda we had discussion about it on [pull/69](https://github.com/meteorhacks/flow-router/pull/69#issuecomment-90900543).

So should we accept blank (`''`) path on route?

**Comment by arunoda** [comment]
I think this is not about that. We need to keep it as like that.
What he's referring to the last "/".
We can remove it when we build the path.

**Comment by VladShcherbin** [comment]
yes, when building a path, we can remove the last **/** and it fill be fine

**Comment by delgermurun** [comment]
Okay, got it.

**Comment by lmacsen** [comment]
Hi there, I am interested in this too.

What about by default no trailing slash for nested routes? But this can be optional, something how Angular ui-router works.

https://github.com/angular-ui/ui-router/wiki/Frequently-Asked-Questions#how-to-make-a-trailing-slash-optional-for-all-routes

**Comment by VladShcherbin** [comment]
@lmacsen hi, why do you suggest it be optional? The urls look ugly, unfriendly and leave a feeling of something *unfinished*. I really don't know, who and why would use trailing slashes. The choice is ok, but I don't think we need it.

**Comment by lmacsen** [comment]
@VladShcherbin I'm on your side. I think the url looks ugly with that trailing slash. The only reason to keep it optional is to minimize the side effects.

What if the user access an url with trailing slash? We have some options:
- 404 (worst case scenario)
- both routes works just fine (like github does, for example: https://github.com/meteorhacks/flow-router/issues/130 vs https://github.com/meteorhacks/flow-router/issues/130/ ) 
- correct that and redirect him silently on correct route

**Comment by VladShcherbin** [comment]
@lmacsen we are not changing the url behaviour in the browser, only for the generated link path (in `<a>` for example).

So, the links `/users` and `/users/` would work the same and show you the users list ;)

**Comment by lmacsen** [comment]
@VladShcherbin

Oh, that's fine. I was thinking about url behavior.

**Comment by rclai** [comment]
Trailing slashes seem like they are a problem.

**Comment by delgermurun** [comment]
@rclai It isn't directly related to this bug. Can you create separated issue?
