### ISSUE TITLE
Chat room?

### ISSUE THREAD

**Issue by VladShcherbin** [meteorhacks/flow-router#131]
Maybe we could create a chat room (for example in [Gitter](https://gitter.im), which is popular for such stuff), where the core team could answer some questions from time-to-time and people, using flow-router/flow-layouts could chat/make advices/best practices. This way, we can even make a FAQ from most asked questions, etc.

Github issues is ok, but faster response and community is far better.

What do you think?

**Comment by arunoda** [comment]
I prefer Github issues since they are all here saved for everyone to read.

**Comment by dcworldwide** [comment]
Agree with @arunoda
