### ISSUE TITLE
[Needs example] Login and checking user permissions

### ISSUE THREAD

**Issue by VladShcherbin** [meteorhacks/flow-router#132]
Okay, for the last couple days I'm trying to implement a roles/permissions system. The idea is that a user has a roles/permissions field in db and this data is automatically published to client for a logged user:

```js
Meteor.publish(null, function () {
  var userId = this.userId,
      fields = {permissions: 1};

  return userId ? Meteor.users.find({_id: userId}, {fields: fields}) : this.ready();
});
```

The problem is with the permission checking: I can't check this (or even check if the user is logged) because of non-reactive middleware.

What I want to do is:
1. user goes to `/admin`
2. if the user is not logged in - show him 404
3. if the user is logged in, check his permissions
3.1. if the user has permission - proceed and show him the page
3.2. if the user does not have permission - show him 404

I guess, this should be somehow done in onCreated template callback, but HOW ?

I use Flow Router + Flow Layout client-side, without fast-render, template-level subscriptions only. I keep trying and trying, but I simply can't do it. Now I am stuck and need help or suggestion, what to do next and how.

Please, help me with that :disappointed_relieved:

**Comment by VladShcherbin** [comment]
After some thoughts, probably, I've done it.

The template:
```html
<template name="adminBasicLayout">
  {{#if permissionsGranted}}
    <div class="admin">
      {{> adminNotifications}}
      {{> adminNav}}
      <div class="contents container-fluid">
        <main>
          {{> Template.dynamic template=main}}
        </main>
      </div>
    </div>
  {{else}}
    {{> spinner}}
  {{/if}}
</template>
```

And its functions:
```js
Controller('adminBasicLayout', {
  created: function () {
    var self = this;
    self.permissionsGranted = new ReactiveVar(false);

    self.autorun(function () {
      if (!Meteor.userId()) {
        FlowLayout.render('notFound');
      } else {
        if (Meteor.user()) {
          if (Meteor.user().permissions) {
            if (Permissions.has(Meteor.userId(), 'admin.login')) {
              self.permissionsGranted.set(true);
            } else {
              FlowLayout.render('notFound');
            }
          } else {
            FlowLayout.render('notFound');
          }
        }
      }
    });
  },
  helpers: {
    permissionsGranted: function () {
      return Template.instance().permissionsGranted.get();
    }
  }
});
```

Can you check, if I'm on the right way or smth should be changed?

Thanks

**Comment by arunoda** [comment]
This is good. That's the way it should work.
Here's the API in my mind

We do this globally in somewhere in my code:

~~~js
var pm = new PermissionsManager({
  loggedOut: "/logout", // after user just loggedOut
  loggedIn: "/" // after user just loggedIn
});
~~~

Here's the template:
~~~html
<template name="secureContent">
  {{#if hasPermission}}
    Render my super secret stuff
  {{else}}
    {{#if authStatusReady}}
      You don't have permission for this page. <br>
      Visit: <a href="/">Home</a>
    {{else}}
      Waiting for authentication
    {{/if}}
  {{/if}}
</template>
~~~

Then, here are the template helpers:
~~~js
Template.secureContent.helpers({
  hasPermission: function() {
    return pm.has("admin.login");
  },
  authStatusReady: function() {
    return pm.ready();
  }
});
~~~

You can also create cool global template helpers as well

**Comment by VladShcherbin** [comment]
@arunoda thank you for your time, example and suggestions.

I tried to decouple users and permissions in my app to use is later in other projects. Probably, I am not that js level now to make a production ready package, especially with some tests. I've pushed to github what I've done so far. The repo is: [here](https://github.com/VladShcherbin/users). It uses accounts-password and permissions system and is what I've done so far.

As for my example above, everything is working as I am expecting except 1 thing - I can't render the 404 page with this code:

```js
Template.adminBasicLayout.onCreated(function () {
  var self = this;
  self.permissionsGranted = new ReactiveVar(false);

  self.autorun(function () {
    if (!Meteor.userId()) {
      FlowLayout.render('notFound');
    } else {
      // ...
    }
  });
});
```

If I use console.log('404') - it works fine, but when using FlowLayout it gives me an error:

![screen shot 2015-05-30 at 12 47 00 am](https://cloud.githubusercontent.com/assets/6711845/7893348/883e9ad8-0665-11e5-9d76-80b33dc70179.png)

Maybe you know, what can cause it? I can make an example repo I guess.

**Comment by arunoda** [comment]
Yeah! Better if we have some code to test.

**Comment by VladShcherbin** [comment]
@arunoda ok, here is the example url: http://users-example.meteor.com
if you go to `/admin` [here is the link](http://users-example.meteor.com/admin), it will give you an error.

Here is the repo:
https://github.com/VladShcherbin/users-example
and the layouts file: [layouts js file](https://github.com/VladShcherbin/users-example/blob/master/client/views/layouts/lib/layouts.js)

**Comment by arunoda** [comment]
This is kind of a bug in flow layout. If the old layout is not rendered yet, if cause some issues.
Here's the quick fix for your app until I fix the issue.

~~~js
Template.securedLayout.onCreated(function () {
  var self = this;
  self.permissionsGranted = new ReactiveVar(false);
});

Template.securedLayout.onRendered(function() {
  var self = this;
  self.autorun(function () {
    if (!Meteor.userId()) {
      //console.log('not found');
      FlowLayout.render('notFound');
    } else {
      // ...
    }
  });
});

Template.securedLayout.helpers({
  permissionsGranted: function () {
    return Template.instance().permissionsGranted.get();
  }
});
~~~

**Comment by arunoda** [comment]
Fixed the flow layout issue as well.
Update flow layout and your code will work.

**Comment by VladShcherbin** [comment]
@arunoda thanks, this was fast ;) I checked it and it worked well.

Some time later I remembered, that we have template helpers (loggingIn, currentUser), they do the same stuff, so I kinda reinvented the wheel in onCreated callback. At least we found a bug.

I've updated the demo repo with template helpers, made a login page, admin page and a simple local package with some permissions and demo users.

The repo link is the same: https://github.com/VladShcherbin/users-example
The demo link now is: http://flow-auth-example.meteor.com

Maybe you can check it, it works exactly the way I want to.

Huge thank you @arunoda . The issue can be closed I guess.

**Comment by arunoda** [comment]
Great.
I'll have some ideas on how the auth system should works in meteor.
I'll do a reference implementation and a blog post in next week or after.

If you could able to do a release, just ping me. I'll add it to in the blog
post.
