### ISSUE TITLE
Allow to use FlowRouter.path() on the server.

### ISSUE THREAD

**Issue by boldkhuu** [meteorhacks/flow-router#135]
Orignal Title: Generate path from a path definition on server side

Is it possible to make `FlowRouter.path()` work on server side? Hardcoding a path is only option for now.

**Comment by arunoda** [comment]
No it's not. What's the use case?

**Comment by boldkhuu** [comment]
On my task management module when I create a new task, I'm sending a notification to its assignees. It's done by creating a new notification on `createTask` method. This notification must have a link to the newly created task details page `/tasks/details/:id`. I think that I need to get this path by route name. But I can't use `FlowRouter.path()` on server side.

**Comment by arunoda** [comment]
Currently, this is not possible. I'll add this to our feature list and
figure out whether this is something we should do it or not.

**Comment by delgermurun** [comment]
:+1:

**Comment by boldkhuu** [comment]
@arunoda Thank you. ;)

**Comment by delgermurun** [comment]
@arunoda can I make a PR for it?

**Comment by arunoda** [comment]
Why not :)

**Comment by delgermurun** [comment]
ok. I'll do it shortly.

**Comment by boldkhuu** [comment]
@delgermurun @arunoda Thank you, guys.

**Comment by arunoda** [comment]
Published with `v1.11.0`
