### ISSUE TITLE
Add method to list known routes, in order

### ISSUE THREAD

**Issue by fightingtheboss** [meteorhacks/flow-router#136]
It would be great to have a Rails-like `rake routes` equivalent, either on the command line or in the client (development only) to be able to see the registered routes in the order they've been registered. As far as I understand, page.js matches routes in the order they're registered, so if you have the following routes:

```javascript
FlowRouter.route('/:username', {...});
FlowRouter.route('/sign-up', {...});
```

You would never be able to access the `sign-up` route because the first one acts as a catch-all. In a trivial example like this it's very clear, but if you have many similar routes, it would be great to see them pretty-printed, in order, so that you can trace conflicts.

I caught this issue when using `useraccounts:core` ([flow-router-integration branch](https://github.com/meteor-useraccounts/core/tree/flow-router-integration)), the solution to which was simply to run `AccountsTemplates.setupRoutes()` before setting up my user routes, but it took a bit of digging.

At the very least, it would be good to have it documented somewhere that routes are matched in the order they're defined, for beginners not familiar with client-side routers.

Thoughts?

**Comment by arunoda** [comment]
We can add a such feature. 
About the docs, I think it should be done in the `useraccounts:core`. Let me link this to there.

**Comment by fightingtheboss** [comment]
Thanks for the quick reply @arunoda! 

I've got a question that's not totally related, but I'm gonna ask it here and we can move it onto it's own issue if it warrants it.

If I have the above-mentioned route `FlowRouter.route('/:username', {...})` that depends on fetching a user profile using `Meteor.users`, where I want to redirect away if the user doesn't exist, what is the correct pattern to do that with Flow Router? So far I've resorted to something like the following:

```js
Template.profile.onCreated(function () {
   this.autorun(function () {
     if ( FlowRouter.subsReady() ) {
       this.user = Meteor.users.findOne({username: FlowRouter.getParam('username')});

       if ( !this.user ) {
         FlowRouter.go('/');
       }
     }
  });
});
```

This seems like a very specific case where I would want to redirect reactively in the router once I determine that there is no user with the provided username, rather than doing this in the template, since I might end up with a flash of content.

Do you have a suggested pattern for this case?

**Comment by arunoda** [comment]
That's something I'm working on with the auth-manager. This is the core
logic.
But, instead of redirect. You can simply display a message and provide a
link to redirect.
Which gives rich UX also. Because the user know what's really happened.

Check this for more: https://github.com/meteorhacks/flow-router/issues/132

**Comment by arunoda** [comment]
You can get the list of routes from `FlowRouter. _routes`. I don't think we need a public API for this.

**Comment by lucatros** [comment]
> At the very least, it would be good to have it documented somewhere that routes are matched in the order they're defined, for beginners not familiar with client-side routers.

I think this suggestion still applies.

**Comment by charlesdeb** [comment]
I use this in the console to get a 'rake routes' out of FlowRouter:

`_.each(FlowRouter._routes, function(route) { console.log(route.path) })`
