### ISSUE TITLE
FlowRouter.triggers.enter should accept single values

### ISSUE THREAD

**Issue by arunoda** [meteorhacks/flow-router#140]
We are not doing any validations for the `FlowRouter.triggers.enter()` and `FlowRouter.triggers.enter()`. So, user can write something this:

~~~js
FlowRouter.triggers.enter(function(context) {
   // do something
 });
~~~

This will do **nothing** because we expect an array for the first arguments. We need to support his case as well. If the first argument is not an function, we need to throw an error.

**Comment by delgermurun** [comment]
So we accept `function` and `array`, right?

**Comment by arunoda** [comment]
Yes. I think giving a function is very natural.

**Comment by delgermurun** [comment]
Yes, you are right. I'll do it shortly.

**Comment by arunoda** [comment]
I'm working on a redirect feature and it needs some refactoring to triggers. So, I'll do it there.
