### ISSUE TITLE
Subscriptions subscribe to root route and then desired route

### ISSUE THREAD

**Issue by avemulkar** [meteorhacks/flow-router#148]
For some reason I just recently received this weird flow regarding subscriptions.  When I navigate from my root route to my desired route (e.g., from '/' to '/home') FlowRouter ends up first calling the subscriptions for the root, then the subscriptions for the desired route, and then again calling the subscriptions for the root.  Hence I end up being subscribed to those subscriptions for the root and not the desired route.

I fixed this by changing my root from '/' to something with a name, such as '/main'.  I think this is just a recent bug... or I may just be doing something wrong.

**Comment by arunoda** [comment]
Can you share your router code which causes this. Then, we can have a look.

**Comment by avemulkar** [comment]
Sure.  The code that caused the behavior is below:

// Route for root
FlowRouter.route('/, {

    action: function() {

        FlowLayout.render('mainLayout', {header: "mainHeader", firstSegment: "XXX",
            secondSegment: null, thirdSegment: "XXX", rightPanel: "XXX"});
    },

    middlewares: [requiredLogin],

    subscriptions:function(){
        this.register('SUB1', Meteor.subscribe('sub1'));

    },
    name: 'root'
});


FlowRouter.route('/home', {

    action: function() {

        FlowLayout.render('mainLayout', {header: "homeHeader", firstSegment: "XXX",
            secondSegment: "emptyTemplate", thirdSegment: "emptyTemplate", rightPanel: "XXX"});
    },

    middlewares: [requiredLogin],

    subscriptions:function(){
        this.register('SUB2', Meteor.subscribe('sub2'));

    },
    name: 'home'
});


The above code worked fine for quite a while (2 months) and only broke today.  On another note I love flowrouter and would like to thank you for putting this project and all the others together!  I'm a huge meteorhacks fan!

**Comment by arunoda** [comment]
There is no something fishy going here. I'd like to have a sample repo. 
I can't figure out the reason.

If you can, try to isolate find out which FR version breaks your app. That helps a lot.

**Comment by avemulkar** [comment]
I upgraded from FR version - 1.9.0 to 1.13.0 and FL version 1.3.0 to 1.4.0  and the problem seems to have gone away.  Would you still like a sample repo?

**Comment by arunoda** [comment]
Nope. We did some fixes.
