### ISSUE TITLE
Passing additional options to FlowRouter.go()

### ISSUE THREAD

**Issue by ildarsamit** [meteorhacks/flow-router#149]
I'm trying to pass additional data to routes (such as how to animate in the new page). Is there a pattern for doing that?

For example, is there a way to do something like:

```
FlowRouter.go(pathDef, params, queryParams, { transition: slideIn'' });
```
```
FlowRouter.route('/page/:pageName', {
  action: function(params, options) {
    renderPage(params.pageName, options.transition);
  },
});
```

I'd appreciate any ideas on how to do something like that. Thanks!

**Comment by VladShcherbin** [comment]
don't think animations is a router part, more like a template layer

**Comment by avemulkar** [comment]
I'd strongly consider using query params.  Reactive vars or session variables are also other options... though query params would be the easiest and cleanest.

**Comment by arunoda** [comment]
@ildarsamit there is no such way. FlowRouter is a router. So, we do only stuff matters with the URL.
You can use query params to pass some state (which is kind a pointer). If you need to pass something big, as @avemulkar mentioned, you can use reactiveVar or something else.

**Comment by ildarsamit** [comment]
Thanks guys. I'll use ReactiveVar for anything that shouldn't appear in the URL.

**Comment by raduchiriac** [comment]
I build my queryParams in advance and I use `FlowRouter.go(FlowRouter.path("homePage", FlowRouter.current().params, queryParams));`
