### ISSUE TITLE
is flow-router to support ie8?

### ISSUE THREAD

**Issue by xurwxj** [meteorhacks/flow-router#150]
when work with flow-router, client with ie8 will get error:
FlowRouter is undefined.

is flow-router to support ie8?

thanks a lot.

**Comment by xurwxj** [comment]
![image](https://cloud.githubusercontent.com/assets/683421/8032579/6f41949e-0e09-11e5-8d73-9c5fced082bf.png)

**Comment by arunoda** [comment]
Yep. We are not yet. But we will soon.

**Comment by arunoda** [comment]
We are tracking this on #111

**Comment by xurwxj** [comment]
thanks,
and what time is expected to support?

**Comment by alanning** [comment]
For reference, #111 added support for IE9 and #264 is tracking IE8 support and already has a solution in the comments.
