### ISSUE TITLE
Broken root URL generation

### ISSUE THREAD

**Issue by lgollut** [meteorhacks/flow-router#151]
It seems that a7313194af04bb0524757b9d5dce242ad15f43cd broke the path generation when we need to reach the root URL. `FlowRouter.path('/')` produce an empty string which is not what we want.

We could correct that by checking if the `pathDef` passed to the function contains a single slash maybe like `pathDef = pathDef.match(/^\/{1}$/) ? pathDef : pathDef.replace(/\/+$/, "");`.

I can submit a PR if that's the way to go.

**Comment by delgermurun** [comment]
@lgollut oh, that's critical bug. Please send PR with test cases.

btw, `path` method defined on server too.
