### ISSUE TITLE
redirect within a trigger or before page rendering

### ISSUE THREAD

**Issue by emmanuelbuah** [meteorhacks/flow-router#153]
Is it possible to redirect from within a trigger. I understand why middleware's were deprecated but being able to direct the flow of route via redirect is very common to routing libs/frameworks. How does flow-router handle these cases without handling redirect after page rendering.

**Comment by arunoda** [comment]
Yes we should have it. We are working on the redirect support for triggers.  But still you can't use reactive content. But, we think this is still useful.

Also, you can look at `FlowRouter.withReplaceState` as well.
See: https://github.com/meteorhacks/flow-router#flowrouterwithreplcaestatefn

**Comment by Goluis** [comment]
+1

**Comment by tomitrescak** [comment]
If I understand this correctly, currently there is no possibility to do authentication within router and we'll have to wait for this functionality in triggers?

**Comment by arunoda** [comment]
Actually, middlewares are not dead yet! 
Doing authentication stuff in the middlewares (or triggers) only works for the first time (with fast render). If that's the case that's fine.

But, we need move the auth logic to the template/view layer. 
See some demo implementation of that: https://github.com/meteorhacks/flow-router/issues/132

**Comment by tomitrescak** [comment]
Arunoda. I followed the examples in the code and came up with following layout which works like charm:

```html
<template name="AdminLayout">
  {{#if isInRole 'admin'}}
    <main id="home">
      <div class="content">
        <div class="ui inverted masthead segment" style="border-radius: 0">
          <div class="ui page grid">
            <div class="column">
              {{> Header }} {{> Template.dynamic template=main }}
            </div>
          </div>
        </div>
      </div>
      <footer>
        {{> Footer }}
      </footer>
      {{> modal}} {{> sAlert}}
    </main>
  {{else}}
    {{ accessDenied }}
  {{/if}}
</template>
```

and helper

```javascript
Template.registerHelper("accessDenied", function() {
	FlowRouter.go("/prohibited");
});
```

Thanks for your help! I just had to get rid of the iron router mindset for authorisations.

**Comment by emmanuelbuah** [comment]
@arunoda I'm a bit confused. Is the future plan to move conditional redirections (like authentication middleware) to pages or its to provide a redirect mechanism in triggers (since middlewares are going away) so we can handle conditional flow. I'm personally not a big fun of the former since its moves routing logic to pages. It also decentralizes middleware logic to pages, hence, any changes to the flow logic will have to be made on all pages using that logic.

**Comment by emmanuelbuah** [comment]
@arunoda why not keep middleware and just rename it to triggers since middleware already has routing flow management (conditions + next()). If I understand what it read, it seems the reason why middleware is being deprecated is because its doesn't perfectly fit the node middleware style.

**Comment by arunoda** [comment]
@emmanuelbuah It's pretty hard to redirects in client apps. Since we don't when we'll get the data from the server. Anyway, you've to wait for the data. While you are waiting for the data, you need to show some loading kind of message to the user.

So, it's logical for me to move it to the view layer. That's the main difference with IR. You can do it with triggers to but that's only for the initial loading. (Since we've the data with Fast Render). 

So, I think it's good idea to do it in the template layer. If you don't like that, I think IR is the best option for you.

**Comment by emmanuelbuah** [comment]
@arunoda Thanks. I appreciate the explanation. I have always been of the impression that we do know when the data arrives via subscription ready notification. If we are using normal ajax, we did wait till the response before any conditional logic based on the received data. 

With that said, I liked flow router for its non reactive nature, its well designed reactive api and the separation of the rendering domain. I was using IR and switched to FR. My app uses a decent amount of conditional routing and will be painful to refactor to move those conditions into a template logic. I will switch back to IR and hopefully give FR a try again on a new project.

**Comment by arunoda** [comment]
Yes, we'll get the ready message. But we don't know when it's arrives.

Yes. You can't do 1-1 mapping with IR with FR. If so, there is no point in building FR rather we could work on IR itself.

**Comment by emmanuelbuah** [comment]
agreed. thanks.

**Comment by Goluis** [comment]
really the lack of middleware has hurt me, but I think that what Arunoda says is true, here I have my own solution (currently testing it in more than 30 routes).

https://github.com/Goluis/cottz-flow-router-auth

**Comment by emmanuelbuah** [comment]
@Goluis  Thanks for the info. Great extension for FR. Auth seems to be the most common conditional routing but there are many more. Example, you might want to redirect users to submit their email if user signs up with a 3rd party service which doesn't provide user email. There are many more situations like that where an api for conditional routing makes things a lot easier. In any case, I think arunoda is right. Its great to have different options for routing to choose from.

**Comment by arunoda** [comment]
I've just submit a PR to support redirects inside triggers. This will help you guys.
See: https://github.com/meteorhacks/flow-router/pull/172

But still you can't have any reactive content inside the Router.

**Comment by v3rron** [comment]
It doesn't work when redirecting within trigger with ``redirect()`` function to a route with ReactLayout. It changes the path correctly but then the page is blank.
````
FlowRouter.triggers.enter([function(context, redirect){
  var currentRouteName;
  Tracker.autorun(function() {
    console.log('Tracker autorun: path changed');
    FlowRouter.watchPathChange();
    currentRouteName = FlowRouter.getRouteName();
  });
  if(!Meteor.loggingIn() && !Meteor.user() && !currentRouteName.in_array(STARTING_ROUTES.concat(BOTH_ROUTES))){
    // Redirect to welcome page whenever trying to reach any non-starting route when user is not logged in
    console.log('redirecting to welcome');
    redirect('welcome');
  }else if(Meteor.user()){
    if(!Meteor.user().profile.first_name) {
      // go to step one if user has not filled his name
      console.log('redirecting to stepOne');
      redirect('stepOne');
    }else if(!Meteor.user().emails) {
      // go to step two if user's email is in the list of restricted emails
      console.log('redirecting to stepTwo');
      redirect('stepTwo');
    }
  }
}]);

FlowRouter.route('/step-one', {
  name: 'stepOne',
  action: function() {
    ReactLayout.render(MainLayout, {
      content: <StepOnePage />
    });
  }
});

FlowRouter.route('/step-two', {
  name: 'stepTwo',
  action: function() {
    ReactLayout.render(MainLayout, {
      content: <StepTwoPage />
    });
  }
});
````
What worked for me is replacing ``redirect()`` with ``FlowRouter.go()``
