### ISSUE TITLE
Using FlowRouter.go("/") does not change the url

### ISSUE THREAD

**Issue by TheMGamer** [meteorhacks/flow-router#154]
I have my home page defined like this.
```javascript
FlowRouter.route("/", {
	name: "home",
	action: function() {
		FlowLayout.render("mainLayout", { content: "home" })
	}
});
```

Using `FlowRouter.go("home")` from somewhere else in my code does not change the URL (it renders the home page). This happens only with "/" as the router's path. If I change the route's path to "/home", it changes the URL normally.

**Comment by VladShcherbin** [comment]
@TheMGamer update to the latest version

**Comment by TheMGamer** [comment]
Thank you.. For some reason, my eyes didn't catch the other thread created for this issue. Sorry!
