### ISSUE TITLE
clicking href="#" link/button will execute action function

### ISSUE THREAD

**Issue by voidale** [meteorhacks/flow-router#156]
Ok so I'm not sure if this expected behaivor but i wasn't expecting it, if you have a link with `href="#"` it will execute the flow router action function on click here is meteorpad:

http://meteorpad.com/pad/tjQayz9kwGCZnpQ6k/Leaderboard
see console and try to click.

**Comment by ildarsamit** [comment]
I don't see a problem with executing the action in this case. You might want to do `onclick` `return false` on the `<a>` element though, so you never arrive at the # URL at all.

**Comment by arunoda** [comment]
I think you need to do `e.preventDefault` or do `return false`. You should not rely on router for this.
Anyway, we are working on some ways to prevent this too.
