### ISSUE TITLE
Pass params and queryParams arguments to global subscription function

### ISSUE THREAD

**Issue by lgollut** [meteorhacks/flow-router#157]
The global subscription function only receives a `path` argument whereas group and route level subscriptions receive `params` and `queryParams` arguments. Is there a reason behind that ?

It seems to me these functions should share the same API, maybe something like that in the main autorun function ?

```javascript
var params = self._current.params;
var queryParams = self._current.queryParams;

...

self.subscriptions.call(self._globalRoute, params, queryParams);
```

**Comment by arunoda** [comment]
That's because it's not tight with any route. Giving `params` or `queryString` seems something weird for me.

In this case, you can get the context via `FlowRouter.current()`. We should pass the context in this case. I like this. I'm open for a PR for that too.
