### ISSUE TITLE
Prevent navigation?

### ISSUE THREAD

**Issue by peterchoo** [meteorhacks/flow-router#158]
Hi all,

Been having a conversation about Routers with a couple of people, and one of the things we were discussing was the lack of clear way to prevent a navigation from taking place.

Imagine a situation where you have a form for creating a blog post, you've filled in quite a lot of it.  In the application when there is text in any of the form fields let's say a Session var gets set to say "editing in progress".  You then click a link (be it by accident or otherwise), and you want your application to show a confirmation modal informing the user that if they carry on their work will be lost.

How can we do this in Flow Router?  

I'm aware that we could have some kind of caching operation to save the form data, and when they come back to the route say "this was saved from before, would you like to use it?", but think that having a way to hook into the navigation and say "if this Session var is true, show this modal".

**Comment by bryankennedy** [comment]
Shouldn't this kind of navigation checking happen before your router call? I agree that this is an important functionality, but it seems like it's more the job of the tool of the editor, or the form handler instead of the router.

**Comment by peterchoo** [comment]
@bryankennedy Sure, I agree that there could be some checking for that, and it is a valid solution, *if* the only way you navigate around your application is using `FlowRouter.go()`.

On the flip side, the only way to create links to other routes is to do something like `<a href={{pathFor 'my.route'}}>Link</a>` if you are using  the flow-router-helpers package, for example.  

How would you suggest I catch these before the navigation happens?

**Comment by arunoda** [comment]
I think this we can't do this kind of things from the Router directly. We'll have idempotent route support here. See: https://github.com/meteorhacks/flow-router/pull/155 

That helps you in one way. But caching kind of things is not what we do and it's hard to prevent user from reloading the page. So, that's a duty of something other package.

So, I'm going to close this now.

**Comment by space-alien** [comment]
@peterchoo Please see my comments on #318 which may be relevant.
