### ISSUE TITLE
Template.autorun running twice on FlowRouter.subsReady()

### ISSUE THREAD

**Issue by fightingtheboss** [meteorhacks/flow-router#159]
I have a very simple setup in a Template like the following: 

```javascript
Template.screening.onCreated(function() {
  this.autorun(function(computation) {
    console.log('In subscription autorun');

    FlowRouter.subsReady();
  });
});
```

When this template is loaded, I see `In subscription autorun` twice in the console.

The `screening` template is loaded in a layout with no logic. I do have two other `this.autorun` statements in the same `onCreated` callback, but I assumed that by doing that they were run in isolated computations.

Is this expected behaviour? I haven't been able to track down why this is occurring.

**Comment by arunoda** [comment]
First time the autorun runs. Second time it runs when you got the
subscription ready message. It's not an issue,

**Comment by fightingtheboss** [comment]
Wow, oh man, sorry, I think that means I need to quit for the day! Yes, of course the autorun callback executes immediately. Thanks for taking the time, sorry again.
