### ISSUE TITLE
Set the website of this GitHub repo to the Atmopshere package

### ISSUE THREAD

**Issue by dandv** [meteorhacks/flow-router#160]
https://atmospherejs.com/meteorhacks/flow-router

**Comment by arunoda** [comment]
I don't find any reason on pointing it to atmosphere. I will leave it
blank.

Why do you think, we should add it to there?

Normally, we don't do that for npm?

**Comment by VladShcherbin** [comment]
If there is a website or github pages - we usually set the top link, if it is only npm/atmosphere/etc - there is usually no link for that.

**Comment by dandv** [comment]
* Atmosphere shows the traction/adoption of a package: number of stars, number of installs, trend
* [Everyone else I've asked to add Atmosphere as the repo's website did it](https://github.com/issues?utf8=%E2%9C%93&q=is%3Aissue+author%3Adandv+is%3Aclosed+atmosphere+github+url), unless there was a better site to add (e.g. components.meteor.com)

It's of course optional :)
