### ISSUE TITLE
Cannot convert object to primitive value

### ISSUE THREAD

**Issue by Goluis** [meteorhacks/flow-router#163]
after upgrading to the latest version of flow-router (1.9.1 to 1.14.1) I found this error
```shell
Exception from Tracker recompute function:
debug.js:41 TypeError: Cannot convert object to primitive value
```
after searching everywhere because I don't know where it came error, I found it on the routes and I have an example here
```js
if (Meteor.isServer) {
	Meteor.publish('home', function (query) {
		check(query, Object);
		return this.ready();
	});
}

var homeSub = new SubsManager();

FlowRouter.route('/home', {
	subscriptions: function (params, query) {
		// note: query is undefined on the server the first time (with fast-render)
		// query = params.query; - consider using this better than using the parameter query
		// with params.query get the same error
		this.register('home', homeSub.subscribe('home', query));
	}
});
```
query is an empty object, but the error is when I subscribe with subs-manager, if instead use Meteor.subscribe all goes well, this broken some routes in my application so I think it's important to report

**Comment by arunoda** [comment]
I hope then, this is more a subs-manager issue. I hope we can move it to there.
I really to have a testable repo. So, we can can fix it soon.
