### ISSUE TITLE
Checking query params raises error

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-router#164]
`check(FlowRouter.current().queryParams, {})` (on page with empty query string).

Raises `Match error: Expected plain object`.

Checking with fields (e.g. `check(FlowRouter.current().queryParams, {page: String})`) raises error too.

**Comment by arunoda** [comment]
So, this is something on server right?
may be related to #163 

Do you have any fix in mind?

**Comment by arunoda** [comment]
I think that's okay. Since null || undefined is not what check expects for?
Is this a bug anyway?

**Comment by delgermurun** [comment]
It is on client. On server it works fine (passing `subscriptions`'s second arg).

It was working fine, but I don't remember when it popped up. Maybe after triggers release.

Yeah, it is bug. I haven't solution yet. My workaround is cloning query params :).
`check(_.clone(FlowRouter.current().queryParams), {})` it works fine.

I guess it is related to #163.

**Comment by arunoda** [comment]
I'm confused.
Where do you use check on the client?
I'd like to have sample case?

**Comment by delgermurun** [comment]
Just copy & paste `check(FlowRouter.current().queryParams, {})` into web console on page with empty query string.

I've shared code that works on client & server. That's why I'm checking on client.

**Comment by delgermurun** [comment]
I find cause of this effect. It is because `qs` use `Object.create` function, so query params doesn't have any properties. Here is commit that changed it https://github.com/hapijs/qs/commit/211ba0fee27550af7d9baa70959f256ac38258f2.

Refs: https://github.com/hapijs/qs/issues/80, https://github.com/hapijs/qs/issues/73

So what should we do?

**Comment by delgermurun** [comment]
Here is error stack trace
```
Error: Match error: Expected plain object
    at checkSubtree (match.js:279)
    at check (match.js:32)
```

Error line: https://github.com/meteor/meteor/blob/devel/packages/check/match.js#L278

**Comment by arunoda** [comment]
I think this is a bug in Meteor. That should boy check for constructor.
For now we can hack convert qs object to a normal object.
