### ISSUE TITLE
Get all params and query params

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-router#169]
It would nice if we have reactive APIs that give all params/query params.

Now, I use `watchPathChange` with `current`.

**Comment by arunoda** [comment]
I think that'll confuse the API and give us a lot. I hope what you are
doing is correct :)

**Comment by delgermurun** [comment]
Okay :).

**Comment by rmuratov** [comment]
For those who gets exact param there'll be no huge difference between

```javascript
FlowRouter.getQueryParam('wow')
```

and

```javascript
FlowRouter.getQueryParams().wow
```

But if you need to get all query params you now have to use feature that is not intended for these purposes

Not so critical of course...

**Comment by arunoda** [comment]
With `FlowRouter.getQueryParam('wow')` we can only depend on `wow` param. But, in other way, we need to depend for all.

That's why we don't(won't) have such an API.
