### ISSUE TITLE
can exit trigger prevent route change?

### ISSUE THREAD

**Issue by jamgold** [meteorhacks/flow-router#170]
I am trying to perform a check on route exit that should possible prevent the route to change (like form entries not saved). How can I abort the route change?

**Comment by arunoda** [comment]
Yes. It'll soon. We are working on that.

**Comment by arunoda** [comment]
I've just implemented it and waiting for others feedback. Could you have a look at [this PR](https://github.com/meteorhacks/flow-router/pull/172). There's a solution for you.

**Comment by jamgold** [comment]
I checked it with the PR but am not sure how it is supposed to work. Are you saying I should `redirect(context.path)` in the exit trigger to abort?

**Comment by arunoda** [comment]
Our redirect API need to have a URL everytime. So, you need to give it like above.

But, you are doing it in the exit handler, so still `context.path` is the current URL. 
So, it tries to redirect to the same URL. Since we've idempotent URLs, route doesn't want.

may be you are looking for direct `stop()` API?

**Comment by jamgold** [comment]
> may be you are looking for direct stop() API?

Yes, I think that would be clean(er).

**Comment by arunoda** [comment]
Got it.

**Comment by arunoda** [comment]
I think we will stick with the redirect API. You don't have a stop API. 
If you need to do more validations, I prefer doing it before routing. 

When user came to a exit trigger, stoping the route make no sense. 
You need to at least change a query parameter to change it.

**Comment by jamgold** [comment]
OK, closing this issue then

**Comment by space-alien** [comment]
@jamgold my comments on #318 may be relevant.
