### ISSUE TITLE
getRouteName needs Tracker autorun?

### ISSUE THREAD

**Issue by VladShcherbin** [meteorhacks/flow-router#171]
From the examples:

> FlowRouter.getRouteName()

>To get the name of the route reactively.

> Tracker.autorun(function() {
>        var routeName = FlowRouter.getRouteName();
>        console.log("Current route name is: ", routeName);
> });

Do we need to use Tracker here? I've used `getRouteName` w/o autorun in 2 places of the app and it is working flawlessly. Am I missing something?

**Comment by arunoda** [comment]
You don't need to have an autoRun. This is get it reactively.

**To get the name of the route reactively.**

**Comment by VladShcherbin** [comment]
@arunoda yes, I understand. I have navigation links and a helper:
```html
<template name="adminNav">
  <nav>
    <ul class="unstyled">
      <li class="{{active 'users'}}">
        <a href="{{route 'admin.users.index'}}"><i class="ion-person-stalker"></i></a>
      </li>
      <li class="{{active 'permissions'}}">
        <a href="{{route 'admin.permissions.index'}}"><i class="ion-unlocked"></i></a>
      </li>
    </ul>
  </nav>
</template>
```

```js
Template.registerHelper('active', function (regex) {
  regex = new RegExp(regex, 'i');

  return regex.test(String(FlowRouter.getRouteName())) ? 'active' : null;
});
```
If the route name passes the regex, I add the *active* class.

This links list is rendered and stays unchanged from route to route and is working reactively without autorun.

**Comment by arunoda** [comment]
Oh yes. It'll work. Template helpers always runs inside an autorun.
I just need to demo it without helpers. That's why I put an autorun.

You don't need an autorun inside a helper.

**Comment by VladShcherbin** [comment]
@arunoda thank you, I just thought that I missed something.
