### ISSUE TITLE
FlowRouter.go throws an error

### ISSUE THREAD

**Issue by pahans** [meteorhacks/flow-router#176]
I have a FlowRouter.go inside a Tracker.autorun.
 ```js
Tracker.autorun(function() {
  if(!Meteor.userId()) {
    FlowRouter.go("/sign-in");
  } 
});
```
throws following error.
![image](https://cloud.githubusercontent.com/assets/1552869/8323013/487419ea-1a5c-11e5-86e1-d4caed86b829.png)

**Comment by arunoda** [comment]
Check the new version. There is a fix for this.

**Comment by ndarilek** [comment]
Seeing this error again in 2.7.0.

I'm using a combination of React and Blaze--ReactLayout to render almost everything, and a React wrapper around the Blaze useraccounts atForm template. Any `FlowRouter.go` call triggers this error:

```
FlowRouter.go("second")
Error: Can't call Tracker.flush while flushing
```

This occurs regardless of whether my pages are React or Blaze-wrapped React components.

Maybe there's an issue detecting whether or not `flush()` should be called in apps where both React and Blaze are used? I don't see this in apps that are primarily Blaze, or in apps that are exclusively React.

If you can't duplicate this, I can post a link to the repository. This happens in a template app that I use as a starter, so there isn't a whole lot of complexity.
