### ISSUE TITLE
FlowRouter.go doesn't work

### ISSUE THREAD

**Issue by zimt28** [meteorhacks/flow-router#177]
I'm using `Tracker` to show a login page if the user is not logged in.
This is what the code looks like:
```
### Client ###

Meteor.startup ->

  # Show Login when the user is not logged in
  Tracker.autorun ->

    FlowRouter.watchPathChange()

    loggedIn = !!Meteor.userId() or Meteor.loggingIn()

    return  if loggedIn

    FlowRouter.go '/login'
```
It's been working all the time, just since yesterday it stopped working (updated to newest versions) - the url will change to `/login` but the action of my login route doesn't run. So I just get the page a user would se if he was logged in. When I then click a link, I will be redirected because of `FlowRouter.watchPathChange()`, so that works.

How can I get this working on page load as well?

**Comment by arunoda** [comment]
It's hard to see by looking at this. Would like to have a kind of sample code we can try out locally.

**Comment by zimt28** [comment]
I'll try to put something together. I've just switched to triggers now, which works. Still prefer to use `Tracker` though.
I think you're building an Auth Manager or so, right? When will we get it? Just thinking if I might just wait for it.
