### ISSUE TITLE
getParam causing exception

### ISSUE THREAD

**Issue by lsunsi** [meteorhacks/flow-router#179]
This simple code

Template.HomeHeader.onRendered ->
	@$('input').val(FlowRouter.getParam('search'))

Is causing this weird error

Exception from Tracker recompute function:
[Log] TypeError: undefined is not an object (evaluating 'currentContext.route') (meteor.js, line 888)

Note: errors trigger only when getParam('search') is not undefined.

I'm posting this here since it seems to be some internal implementation issue, but maybe I'm wrong.

**Comment by arunoda** [comment]
I can see where this coming from. But can't sure why it's happening. Is it possible for you to give me a sample code where I can replicate this.

**Comment by arunoda** [comment]
Try the latest version. I fixed a potential issue.

**Comment by lsunsi** [comment]
It is fixed! Thanks :D 
you sure was quick haha

Anyway, quick random question:
how is the correct way of using a Meteor.user() info inside a router 'subscriptions'?
since Meteor.user() is reactive, I shouldn't use inside router, right?

**Comment by arunoda** [comment]
Try to ignore if possible.
