### ISSUE TITLE
Before hook and route name?

### ISSUE THREAD

**Issue by Kestanous** [meteorhacks/flow-router#18]
I know this is still a work in progress but I hope to add support for flow to kestanous:candid and kestanous:herald. Are there thoughts and/or options for the following?

Candid will need some kind of before hook that tells it what the current route is, and if it should stop the route (this may work at the component level as well).

Herald will just need to know the current route reactively (to mark notifications as read) and be able to take a user to a route (this may even just trigger some logic, it depends on flow).

No rush on replying, just try to get in the queue ^_^

**Comment by arunoda** [comment]
Okay. We've the support for both.

* middlewares for candid
* FlowRouter.current() for the herald

Hope we can release soon :)

**Comment by arunoda** [comment]
Flow Router is now ready :)

**Comment by Kestanous** [comment]
Awesome! I will check it out first thing Monday. Candid support should be the easiest.

**Comment by arunoda** [comment]
Great.

**Comment by arunoda** [comment]
Hope we got all you need :)
