### ISSUE TITLE
Define custom properties on your routes

### ISSUE THREAD

**Issue by robertpitt** [meteorhacks/flow-router#181]
Hey guys,

It's looking like were all starting to switch to flow-router due to the problems arising in iron-router, but for myself and my team, there's still a few flexibility teething issues that id like to open to the forum.

So the issue we are trying to solve is dealing with roles and routes.

We have come up with an approach we all think is clean, here's an example router file.

```js
Router.route("/admin", {

    /**
     * Route name
     */
    name: 'admin',

    /**
     * Roles required for this route
     */
    roles: ['admin', 'staff', 'god'],

    /**
     * Action to render the view file.
     */
    action: function(){}
});
```

And then we would have a separate single tracker auto-run to monitor route changes and check the permissions accordingly.

```js
Tracker.autorun(function(){
    Router.watchPathChange(); // depends

    Router.current().route.roles === undefined; // HERE
});
```

As you can see the problem lies in not being able to access `roles` reference, why, well quite simply because your main route file cherry picks only the required properties and ignores everything else.

What are the chances of changing this around to validate required properties, but use `_.extend(this, options)` to mixin everything.

It would be pretty helpful.

Regards.

**Comment by arunoda** [comment]
I see what you looking here. But, I am not planning to add this kind API to flow-router soon. At least for 2.x.
May be you can create a map with route names to roles externally.
You can define it inside the actions. So, it'll be looks like integrated into the route.

**Comment by robertpitt** [comment]
@arunoda, thanks for the response.

I assumed you would probably take that approach, the external mapping is the solution we have decided to go with until a cleaner solution is available.

Thanks.
