### ISSUE TITLE
Rendering React components does not work on versions above 1.14.1 

### ISSUE THREAD

**Issue by guilhermedecampo** [meteorhacks/flow-router#183]
Hello @arunoda !

Thanks for this clean router is pretty awesome.

Unfortunately I can't render React components on `action` method in versions above 1.14.1.
Seems that flow-router can't see the `<div id="container"><//div>` in the DOM. 

I made an app to reproduce:

https://github.com/guilhermedecampo/repro-react-flow-router

How can we work on this problem?
Thanks

**Comment by arunoda** [comment]
Let me look at it.

**Comment by arunoda** [comment]
Yep. Now Flow Router does not wait for DOM. We do it in the layout layer. For now, you can do this:

~~~js
FlowRouter.route('/', {
  action: function() {
    $(function() {
      console.log(document.getElementById('container'));
      React.render(
        React.createElement(HomeScreen, null),
        document.getElementById('container')
      );
    });
  },

  name: 'home'
});
~~~

But we are working on a react layout.

**Comment by guilhermedecampo** [comment]
Ok cool @arunoda !

Let me know about the react layout.

**Comment by gabrielhpugliese** [comment]
Without IE8
```
document.addEventListener("DOMContentLoaded", function(event) { 
  React.render(
        React.createElement(HomeScreen, null),
        document.getElementById('container')
      );
});
```

**Comment by arunoda** [comment]
Meteor.startup is equivalent to this.

**Comment by arunoda** [comment]
May be not.

**Comment by gabrielhpugliese** [comment]
Don't think so :)

**Comment by gabrielhpugliese** [comment]
Actually, I was thinking about this. The startup docs say:
`On a client, the function will run as soon as the DOM is ready.`
So, it would run if the `div#container` is present on DOM. But, in this case, it doesn't mean that div is present on DOM when the it is ready. I think none of those solutions will work, since we doesn't have a callback to the div we want.
Does it make sense?

**Comment by arunoda** [comment]
May be. `$` is something working at the moment. So, that's why I suggested.

**Comment by gabrielhpugliese** [comment]
Maybe because it's deferring the execution only. It needs to be debugged.

**Comment by arunoda** [comment]
May be Meteor.start() and Meteor.defer() inside it, as we do it for
onRendered callbacks.

**Comment by gabrielhpugliese** [comment]
:+1:

**Comment by arunoda** [comment]
We'll be launching ReactLayout soon. 
And I hope there is a fix for this issue.

**Comment by guilhermedecampo** [comment]
Can you notify us @arunoda ? Thanks!

**Comment by damonmcminn** [comment]
@guilhermedecampo: ReactLayout has been published - https://atmospherejs.com/kadira/react-layout

**Comment by guilhermedecampo** [comment]
Awesome @damonmcminn. Thanks for letting us know!!!
