### ISSUE TITLE
[bug?] Unexpected "There is no route for the path: /" errors in console

### ISSUE THREAD

**Issue by raibutera** [meteorhacks/flow-router#185]
## Problem Description

I have a route that works with the following definition at the bottom of a jsx file:

```javascript
FlowRouter.route("/", {
    subscriptions: function(params, queryParams) {
        // if(queryParams && queryParams.email){
        //     this.register('runwayEventsForEmail', Meteor.subscribe('runwayEvents', queryParams.email));
        // }
    },
    action: function(params, queryParams) {
        ReactLayout.render(ReactChanApp);
    }
});

```

`ReactChanApp` renders as expected, but I keep getting errors from `utils.js` saying the route is missing, e.g: `There is no route for the path: /`

## DEMO

https://github.com/raibutera/flow-router-185

`npm install && cd app && meteor`

**Comment by arunoda** [comment]
Could you wrap this code into a github repo as a package and share it here.  And remove all the source code from the issue.

**Comment by raibutera** [comment]
I've updated the OP and removed src code. 

Will have a package up on github in the next hour or so.

**Comment by raibutera** [comment]
@arunoda please see Issue 185 Demo repository, added to the OP.

**Comment by arunoda** [comment]
Sure. I will go with this.

**Comment by arunoda** [comment]
Problem is you are using both `flow-router` and `flow-router-ssr` at [once](https://github.com/raibutera/flow-router-185/blob/master/app/.meteor/packages). Remove one of them app will work properly.

**Comment by sergiotapia** [comment]
I'm having this error @arunoda. My packages are:

```
meteor-platform
underscore
semantic:ui
flemay:less-autoprefixer
meteorhacks:flow-router
kadira:react-layout
```
My `router.jsx` file is:

```
FlowLayout.setRoot('body');

FlowRouter.route('/', {
    triggersEnter: [requiredLogin],
    action: function() {
        ReactLayout.render(AppLayout, {
            content: <App />
        });
    }
});
```

Exact error is: `There is no route for the path: /`

**Comment by churcho** [comment]
@sergiotapia is your router.jsx file in a package? If so, is the package being included in meteor either by api.use within the main package or included using meteor add?

**Comment by Sergiodfdez** [comment]
I have the same problem when i use with phone gap, a provisional fix that work for me is the next:

```js
var mainRouter=FlowRouter.group({});
mainRouter.route('/',{action:function(){ 
     BlazeLayout.render("login")
}});
```

**Comment by judsonbsilva** [comment]
@sergiotapia, are you installed the meteor-react package? If not, your .jsx files don't are read.

**Comment by iboxgithub** [comment]
it is indeed an error that appears when you didn't "meteor add react" :)

**Comment by joetidee** [comment]
Any chance of adjusting this so that I can use the npm react package rather than the atmosphere one?

**Comment by fvpDev** [comment]
Any update on this?

**Comment by arrygoo** [comment]
Experiencing this since migration to 1.4.1 and react-mounter and react 15

**Comment by thiagocoelho** [comment]
In my case I was using a prefix like:

```
  const prefix = '/';
  const routes = FlowRouter.group({prefix});

  routes.route("/", {
    action() {
      mount(SiteLayoutContainer, {
        context: context,
        content: <HomeContainer context={context} />
      });
    },
  });
```

Once I removed the prefix `'/'` everything worked like a charm.
