### ISSUE TITLE
How to make a VERY simple router?

### ISSUE THREAD

**Issue by ccorcos** [meteorhacks/flow-router#190]
I really liked Flow Router when it was super simple. But its getting more complicated and supporting more features so I'd like to make another router thats stripped of all the bells and whistles.

This is all I want to be able to do:

```coffee
Router.route '/some/:route/', (params, queryParams) ->
  # do something here

Router.go '/go/somewhere/else'
```

Any suggestions on where to start and what I can strip?

**Comment by ccorcos** [comment]
I figured something out:

https://github.com/ccorcos/meteor-client-router

**Comment by arunoda** [comment]
I see what you are referring to.
But, how it becomes complicated?
All the additional features are optional.

**Comment by arunoda** [comment]
I agree some of these features are not needed for some apps. But, it's vital when building a router for everyone. The syntax, you show it still valid and we didn't break the simplicity.

Didn't it work.

**Comment by ccorcos** [comment]
Yes, FlowRouter was working just fine

**Comment by arunoda** [comment]
BTW: It's nice to see more routers.
It'll help someone who want something super simple like you :)

**Comment by ccorcos** [comment]
Yep :)
