### ISSUE TITLE
SSR: controlling http response headers? 

### ISSUE THREAD

**Issue by rclai** [meteorhacks/flow-router#191]
Given that SSR is now doable (well done!) , will there be any way to control response headers, like for example, the http code? This will be pretty important for SEO.

For example, trying to subscribe to data that doesn't exist will need to give a 404.

**Comment by arunoda** [comment]
server side 404 is planned with 3.0. I'm quite not sure how to do it and APIs.
But, it'll be there.

Tracking it here: https://github.com/meteorhacks/flow-router/issues/84
