### ISSUE TITLE
A way to keep the trailing slash ?

### ISSUE THREAD

**Issue by ybycode** [meteorhacks/flow-router#192]
Is there a way to keep the trailing slash ? I have static HTML content (generated by sphinx-doc) with relative URLS and can't make it work with FR.
In previous versions of FR I used a middleware to force the trailing slash (next(path + '/') where needed), but this doesn't work with triggers as the redirect function removes the trailing slash.
Any idea ?

Thanx

**Comment by arunoda** [comment]
Yes, We removed that. Web is quite okay without it.
Our router supports both. But we don't generate them.

BTW: I can't understand the usecase. 
Can you provide us a detail case. May be with a sample repo.

**Comment by ybycode** [comment]
It's not FR doesn't generate them, it's actually it *removes* them..
My use case is as follows: I have static HTML documentation. This content contains internal links to other documentation pages of the site, which doesn't have a leading slash, ie <a href="some/page">some page</a>. 
What happens is when I'm on the page http://127.0.0.1/doc and I click this link, the browser tries to reach http://127.0.0.1/docsome/page, instead of http://127.0.0.1/doc/some/page.

**Comment by arunoda** [comment]
Good call.

**Comment by arunoda** [comment]
Implemented https://github.com/meteorhacks/flow-router#flowrouterwithtrailingslashfn

**Comment by arunoda** [comment]
Released with 1.18.0

**Comment by ybycode** [comment]
Great ! Thanks, it works perfectly !

**Comment by rclai** [comment]
This is nice but would it be too much to ask for an API that configures routes to always have trailing slashes whenever you call `go` or `setParams`?

**Comment by arunoda** [comment]
~~~js
FlowRouter.goX = function(path, params, queryParams) {
  FlowRouter.withTrailingSlash(function() {
    FlowRouter.go.call(FlowRouter, path, params, queryParams);
  });
};
~~~

:D

**Comment by Alino** [comment]
+1 for clearer way to configure it globally for flowRouter to always keep the trailing slash. Without making custom functions
