### ISSUE TITLE
Notfound breaks unit test suite

### ISSUE THREAD

**Issue by marcodejongh** [meteorhacks/flow-router#195]
For dependency management purposes I have the dependency to FlowRouter inside the application's Core package. And I test all application packages using ```mike:mocha-package``` and driver-package ```respondly:test-reporter```.

When I run my test suite and I have a notFound route it breaks the test reporter because the router doesn't know the route and calls the notFound handler.

FlowRouter should be disabled when unit testing. It only makes sense for integration testing.

I can work around it with by moving the notFound route to the application itself.

**Comment by arunoda** [comment]
We can't decide whether it's testing or not. 
But there's a way to stop flow-router. May be you can do it for your app.

See: https://github.com/meteorhacks/flow-router#flowrouterwait-and-flowrouterinitialize

I think that's the best thing to do.

**Comment by marcodejongh** [comment]
@arunoda Yeah it's kind of hard to tell. So I've just moved the notFound route to the application itself. That way it doesn't get initialised in the unit test suite.

**Comment by arunoda** [comment]
So. I'm gonna close this now.
