### ISSUE TITLE
Question: app layout / where to put router.js

### ISSUE THREAD

**Issue by TomFreudenberg** [meteorhacks/flow-router#196]
Hi, is it generally suggested to put the router.js into common lib part for client and server if using flow-router and flow-layout?

**Comment by arunoda** [comment]
Yes it is.
If you use subscriptions on the client, It support fast-render.
That's the only reason for now.

We'll have SSR in 3.0. So, then that'll help too.

**Comment by TomFreudenberg** [comment]
Thanks for your fast reply, I just wanted to make sure that I took the conclusion out of your documentation

Cheers
Tom
