### ISSUE TITLE
withReplaceState trigger triggers.enter again.

### ISSUE THREAD

**Issue by WooGenius** [meteorhacks/flow-router#197]
Hi Arunoda

When I use `setParams()` only, this doesn't trigger `FlowRouter.triggers.enter()` if page is on same route.
But when I use `setParams()` with `withReplaceState()` like 
```javascript
FlowRouter.withReplaceState(function(){FlowRouter.setParams({a: "bf"});})
```
It triggers `FlowRouter.triggers.enter()` again even when it's on same route. Is this intended?

**Comment by arunoda** [comment]
Every change in the URL should goes inside a enter trigger. So, this seems like a bug. 
Let me look at it.

**Comment by WooGenius** [comment]
Even when page is on same route?
Then how can I correct a part of url without enter trigger's being triggered . Just directly use history.replaceState?

**Comment by WooGenius** [comment]
Ah okay got it. Thanks for your reply.

**Comment by arunoda** [comment]
Fixed the issue with https://github.com/meteorhacks/flow-router/commit/ec2e90f60dd675c9b8baa700d360ece30f012de7

@WooGenius seems like you need this https://github.com/meteorhacks/flow-router/issues/184

**Comment by arunoda** [comment]
Let's carry over the discussion there.

**Comment by WooGenius** [comment]
Wow so fast thanks a lot!!
