### ISSUE TITLE
Hook on loaded

### ISSUE THREAD

**Issue by tomitrescak** [meteorhacks/flow-router#198]
Hi

This is probably just another iron router functionality, but is it possible to hook onto "loaded" of the template? I would like to add some page transitions and am lazy to put it in every single template.

In IR that was done in "loaded" hook.

Thanks

**Comment by arunoda** [comment]
Sorry. FR don't do any template stuff.
This should be move into Flow Layout maybe.
But I suggest you to use Mixins and Blaze Components to avoid redundancy.
