### ISSUE TITLE
Sitemaps with flow-router

### ISSUE THREAD

**Issue by nikhildaga** [meteorhacks/flow-router#199]
I am using https://github.com/gadicc/meteor-sitemaps .
How can I load sitemaps.xml with flow-router?

**Comment by arunoda** [comment]
I think sitemaps are not directly configured with flow-router of client side router.
Read their docs a bit more: https://github.com/gadicc/meteor-sitemaps

**Comment by nikhildaga** [comment]
Thanks @arunoda . Is there any other way I can create automated sitemaps?

**Comment by arunoda** [comment]
Not something I am aware of.
