### ISSUE TITLE
need a way to remove query params

### ISSUE THREAD

**Issue by pahans** [meteorhacks/flow-router#20]
we can add  query params to URL but we cannot remove them.

**Comment by arunoda** [comment]
If the param is `null` or `undefined` let's remove it.

**Comment by elidoran** [comment]
+1  
That sounds good to me.

Do setQueryParams(null) to remove all query params?
Do setQueryParams({keep: 'value', deleteThis:null}) to remove the one query param?

**Comment by arunoda** [comment]
May be we can have a separate apis for these as well. I think that's much clear.

**Comment by Goluis** [comment]
I just spent my application to Flow-router and I am creating a package for this, because in most of the routes I handled everything with path, the package only lacks documentation but I'll upload it today

**Comment by Goluis** [comment]
here it is: [cottz-flow-router-query](https://github.com/Goluis/cottz-flow-router-query)

**Comment by arunoda** [comment]
Let's carry over the discussion here: https://github.com/meteorhacks/flow-router/pull/60
