### ISSUE TITLE
How do I use a subscription in flow-router?

### ISSUE THREAD

**Issue by sergiotapia** [meteorhacks/flow-router#201]
// server/publications.js
    Meteor.publish('crewMessages', function(crewId) { 
      return CrewMessages.find({crewId: crewId}, {sort: {submitted: -1}, limit: 100});
    });
    
    // lib/router.js
    FlowRouter.route('/crew/:crewSlug', {
        subscriptions: function(params) {
            console.log("Subscribed to this crew's chat messages:", params.crewSlug);
            this.register('crewMessages', Meteor.subscribe('crewMessages', params.crewSlug));
        },
        action: function(params) {
          FlowLayout.render("layout", { content: 'crew' });
        }
    });

And inside my `crew.html` template:

    <div class="container">
      {{> crewChat}}
    </div>

And my `crewChat.html/js`:

    Template.crewChat.helpers({
      messages: function() {
        // right here - is this correct?
        return CrewMessages.find({}, {sort: {submitted: -1}}); 
      }
    });

    <div class="ui feed">
      {{#each messages}}
        {{> crewChatMessage}}
      {{/each}}
    </div>

In my `crewChat.js` file, how can I use the subscription I set in Flow-router?

**Comment by TomFreudenberg** [comment]
Hi Sergio, just to complete here, you asekd the same question on StackOverflow: 

http://stackoverflow.com/questions/31354788/how-do-i-use-a-subscription-in-flow-router/31356083#31356083

And here is the running MeteorPad:

http://meteorpad.com/pad/Ba5DTe94NjFi3ZTPA/Playground_Flow-Router_Chat

Maybe you close your issue if it is clear for you right now

Cheers,
Tom

**Comment by sergiotapia** [comment]
Yeah, thanks for reminding me to close this. Hope this helps other people as well.
