### ISSUE TITLE
Documentation addon: Flow-Router example

### ISSUE THREAD

**Issue by TomFreudenberg** [meteorhacks/flow-router#204]
Hi @arunoda 

Due to a stackoverflow question today I made a simple MeteorPad for a Flow-Router example.

Maybe you like to add this to your README as a running example.

http://meteorpad.com/pad/Ba5DTe94NjFi3ZTPA/Playground_Flow-Router_Chat

Cheers
Tom

**Comment by arunoda** [comment]
Thanks, We are working on a new guide.
Will add to that.
