### ISSUE TITLE
triggersExit TypeError: trigger is not a function

### ISSUE THREAD

**Issue by jholl** [meteorhacks/flow-router#206]
**v1.18.0**
Is anyone else having issue with this?  I have some grouped routes and solo routes, say:

```
projectsRoutes = appRoutes.group({
    prefix: '/projects',
    triggersEnter:[RouteTriggers.setSessionScopeObjectCollection("Projects")],
    triggersExit: [RouteTriggers.removeSessionScopeObject]
});
```

in a helper file I have the object RouteTriggers (I know it's not a load order issue because it is in the only subdirectory within my routes dir ... and other RouteTriggers functions are working fine within `actions`)

But just to be sure, I moved the function into the bottom of the projectRoutes file, like in the docs

```
projectsRoutes = appRoutes.group({
    prefix: '/projects',
    triggersExit: [removeSessionScopeObject]
});

var removeSessionScopeObject = function(context){
   if(Meteor.isClient){
       Session.set('scopeObjectCollection', undefined);
   }
}
```

Still I get the error `TypeError: trigger is not a function`

If I run any of these functions within the `actions`, then I get the desired result.  The triggersExit is ideal for me because I want to clean up Session info to make sure it doesn't unintentionally carry to another scope before I set it again.

triggersEnter and triggersExit are working great for everyone else, on groups, and single routes within groups?  Passing in other args instead of `context`? Let me know if I should move this to SO.

**Comment by arunoda** [comment]
You code is a bit incorrect. In JS we've function hoisting. Not variable hosting. So you need to write this like this:

~~~js
projectsRoutes = appRoutes.group({
    prefix: '/projects',
    triggersExit: [removeSessionScopeObject]
});

function removeSessionScopeObject(context){
   if(Meteor.isClient){
       Session.set('scopeObjectCollection', undefined);
   }
}
~~~

**Comment by arunoda** [comment]
I hope this solves your issue.

**Comment by jholl** [comment]
Thanks, it does.

**Comment by lucasdavid** [comment]
I'm having this problem using `AccountsTemplates.ensureSignedIn`:

```javascript
import {FlowRouter} from 'meteor/kadira:flow-router';
import {BlazeLayout} from 'meteor/kadira:blaze-layout';
import {Accounts} from 'meteor/accounts-base';
import {AccountsTemplates} from 'meteor/useraccounts:core';

const privateRoutes = FlowRouter.group({
    triggersEnter: [AccountsTemplates.ensureSignedIn],
});

// further declarations...
```

Finally, the client's console outputs `TypeError: trigger is not a function`.
