### ISSUE TITLE
How to change Component state when URL changes in React

### ISSUE THREAD

**Issue by SenerDemiral** [meteorhacks/flow-router#207]

**Comment by arunoda** [comment]
Check our API: https://github.com/meteorhacks/flow-router#api

You can get URL state reactively. Then you can use it inside `getMeteorData`

**Comment by SenerDemiral** [comment]
I tried to change TabPane of TabbedArea based on URL.

**Comment by arunoda** [comment]
It's hard to answer like this without seeing anything. Would you like to have a sample repo with a problem.

**Comment by SenerDemiral** [comment]
Thank you anyway. This was not problem but question about component comminication.

**Comment by arunoda** [comment]
Okay. Here's the normal way to do communication in Meteor and React.
There is a layer of components where they fetch data manage Routes.

Then there is another layer of components, which accepts data as actions as props. They don't use states at all. This is successful way to model React Meteor apps.

I'm closing this issue, but feel free to discuss.
