### ISSUE TITLE
flow-router-ssr: route action context = null ?

### ISSUE THREAD

**Issue by nowakstefan** [meteorhacks/flow-router#209]
```javascript
FlowRouter.route("/foo/:bar?", {
 name: "superfoo",
 action: function (params) {
  console.log("name", this.name); // works on the client BUT not on the server
  console.log("params", params); // works on both client & server
 }
});
```

It should be possible to access this value.

![image](https://cloud.githubusercontent.com/assets/2981250/8712881/f98473cc-2b61-11e5-9515-f5d416b27b17.png)
https://github.com/meteorhacks/flow-router/blob/ssr/server/route.js

Why is the context here set to null and not to self (as it is in the subscriptions block) or at least a cleaned-up context version?

**Comment by arunoda** [comment]
It's bug. send me a PR :)

**Comment by nowakstefan** [comment]
thanks for your quick response :+1: :)
