### ISSUE TITLE
Meteor in production with flow router `There is no route for the path: / `

### ISSUE THREAD

**Issue by 416serg** [meteorhacks/flow-router#212]
Running `meteor --production` resolves in a `There is no route for the path: /` error.

Here's my `router.js`

```
FlowRouter.route('/', {
  name: 'home',
  action: function (params, queryParams) {
    // var route = "home"+TAPi18n.language()
    FlowLayout.render('layout', { top: 'header', main: 'home' });
  },
})
```

**Comment by arunoda** [comment]
It really hard to answer like this. Please send us a sample repo.
May be you have two versions of FlowRouter. Hope you are not using our SSR version. If so, remove one.

**Comment by 416serg** [comment]
it was an error i was having somewhere else that caused the router not to load and display that error, everything works, keep up the great work!
