### ISSUE TITLE
[bug] actions not fired.

### ISSUE THREAD

**Issue by trusktr** [meteorhacks/flow-router#213]
Hi @arunoda, I'm trying the README example, using v1.18.0. I have this:

```js
FlowRouter.route('/blog/:postId', {
    // an array of middlewares (we'll discuss about this later on)
    middlewares: [],

    // define your subscriptions
    subscriptions: function(params, queryParams) {

    },

    // do some action for this route
    action: function(params, queryParams) {
        console.log("Params:", params);
        console.log("Query Params:", queryParams);
    },

    name: "<name for the route>" // optional
});
```

and then I do this

```js
FlowRouter.go('/blog/my-post?comments=on&color=dark');
```

but nothing is outputted to the console, although the browser URL *does* change to `/blog/my-post?comments=on&color=dark`.

I also tried

```js
FlowRouter.route('/', {
    action: function(params) {
        console.log('home!', params)
    }
})
```

and there's not output in the console when visiting `/`.

**Comment by trusktr** [comment]
It's working now. I didn't change any code whatsoever, the only thing I did was modify `.meteor/packages` and `.meteor/versions` in order to remove flow-router and cosmos:browserify, and/or downgrade flow-router, then it started working, then I went up minor version by minor version back up to 1.18.0, and it just worked. No code changes at all! I've no idea what happened. Perhaps some weird fluke in Meteor's build system (or possibly with cosmos:browserify)?

**Comment by arunoda** [comment]
May be. Meteor package system is a pain sometimes.

One tip: You need to stop a running app before upgrade.

**Comment by trusktr** [comment]
I noticed that! That might be why.

**Comment by pprasanth** [comment]
@trusktr to which version downgraded?
