### ISSUE TITLE
Support for # anchors

### ISSUE THREAD

**Issue by proehlen** [meteorhacks/flow-router#214]
Hello, thank you for your excellent router.  

I'm using bootstrap and on mobile I would like to use anchors to support navigation within a page where details are often off screen and not obvious to the user. I understand that Meteor has issues supporting vanilla HTML anchors due to the way pages are rendered.  However, it appears that Iron Router has some support built in for this http://www.wsvincent.com/meteor-anchor-tags-hack/ .

Would it be possible to have something similar added to Flow Router?

**Comment by arunoda** [comment]
As far as I know it works by default. We don't need special handling. But, we need to have data rendered on the screen. 

See: https://kadira.io/academy/getting-started-with-kadira#auto-connect

This works pretty well. 
You can use `FlowRouter.go()` but direct linking works.

**Comment by proehlen** [comment]
Ok, must be an issue with the rendering of my data.  Thanks for you time and the working example.

**Comment by markoshust** [comment]
This might need to be reopened. It works when first entering a route (as provided example), however when linking to an anchor inside an already-rendered component, it doesn't work.

I had to listen on the next tick to get things working with React. Called this handler function like so:

```
  handleRequestLinkClick() {
    FlowRouter.go("home");

    setTimeout(function() {
      document.location = '#requestinvite';
    }, 0);

    return false;
  },
```

**Comment by talha-asad** [comment]
@arunoda Alot of times Kadira keeps showing the `loading ...` message, Is this a known issue?

**Comment by moritaka** [comment]
The link of the example has expired.
https://kadira.io/academy/getting-started-with-kadira#auto-connect

How can I see it?
