### ISSUE TITLE
Clicking a link with a relative path works out of the box?

### ISSUE THREAD

**Issue by trusktr** [meteorhacks/flow-router#215]
I have

```html
<a href="/path"></a>
```

and when I click the link the router works! I didn't have to do

```js
Template.x.events({
  'click a': function(e) {
    e.preventDefault()
    FlowRouter.go('/path')
  }
})
```

Is this handled by flow-router? Handled by Meteor?

**Comment by arunoda** [comment]
Links are normally handled by flow-router. `FlowRouter.go()` if you need to do it manually.

**Comment by trusktr** [comment]
Where's the code that handles those links?

**Comment by arunoda** [comment]
It's done by page.js the library we use behind the scene.

**Comment by sahanDissanayake** [comment]
Having this issue right now 
https://forums.meteor.com/t/meteor-reactjs-why-reloading-page/9972/5

I need to prevent the link click, but need the href to be there for SEO, Do not know why I cannot use

```
e.stopPropagation();
        e.preventDefault();
        return false;
```

to stop the click even

**Comment by sahanDissanayake** [comment]
maybe similar to this https://github.com/kadirahq/flow-router/issues/156
