### ISSUE TITLE
Routes by name?

### ISSUE THREAD

**Issue by ccorcos** [meteorhacks/flow-router#22]
FlowRouter.route('/blog/:postId')

I'm getting an error 

There is no route for the path: /blog

How can I use FlowRouter.go?

FlowRouter.go('/blog', {postId:postId})?
FlowRouter.go('blog', {postId:postId})?
FlowRouter.go('/blog/'+postId)?

**Comment by arunoda** [comment]
Router.go does not automatically get the path. You need to specify that.
Like this:

~~~
FlowRouter.go('/blog/:postId', {postId: 'something'})
~~~

or you can also try:

~~~
FlowRouter.go('/blog/' + 'something');
~~~

**Comment by ccorcos** [comment]
ok

**Comment by Sergiodfdez** [comment]
I have the same problem when i use with phone gap, a provisional fix that work for me is the next:

```js
var mainRouter=FlowRouter.group({});
mainRouter.route('/',{action:function(){ 
     BlazeLayout.render("login")
}});
```
