### ISSUE TITLE
Question: Is there any way to check if path is defined before router triggered?

### ISSUE THREAD

**Issue by WooGenius** [meteorhacks/flow-router#221]
HI Arunoda.
I'm implementing server side not found. I want to send 404 response if path is not defined on router which is placed on `lib` folder. So is there any way to check if path is defined on router or not on server side??

Thanks in advance.
Woo Jin.

**Comment by arunoda** [comment]
This no possible right now. It's comes with FR 3.0 which has SSR support. We are working on that in the `ssr` branch but not yet implemented this functionality yet.

**Comment by arunoda** [comment]
We track this here: https://github.com/meteorhacks/flow-router/issues/84
