### ISSUE TITLE
SSR with Blaze

### ISSUE THREAD

**Issue by timothyarmes** [meteorhacks/flow-router#222]
Hi,

Can you please tell me if the the upcoming SSR support will allow for Blaze templates? I've been looking through the code on the SSR branch and I notice that you add the rendered HTML to a 'react-root' DIV. Do you only plan to offer SSR support for react?

**Comment by arunoda** [comment]
We build all the tools for SSR and I'd like to do it for Blaze. But unfortunately, Blaze templates don't available on the server. That's the issue.

If meteor add that, then we can try that too. (I hope it'll work too)

**Comment by arunoda** [comment]
I'm doing a webinar next monday and talk more about these.

**Comment by timothyarmes** [comment]
OK. So the current state of affairs is that we **have** to use React to get SSR.

I'm happy to use React in principle, but the big stopping point is that important existing packages (such as Meteor Accounts) use Blaze.

**Comment by arunoda** [comment]
I get it.
May be this project can help that: https://atmospherejs.com/timbrandin/sideburns

**Comment by timothyarmes** [comment]
Interesting project, but it doesn't solve the problem since packages aren't (yet) providing the .html.jsx templates.

**Comment by arunoda** [comment]
yep. got it.

**Comment by timothyarmes** [comment]
The Meteor tutorial for using React calls Blaze.render inside a React Class:

http://tutorial-viewer.meteor.com/tutorial/8/react

Do you know what will happen if we try to do that using Flow Router?

One possible solution we have here is to only call Blaze.render on the client. That way the SSR rendered version won'd include the login template, but that's really not too bad.

**Comment by arunoda** [comment]
Then, those templates also won't available on the server. Same rules.

**Comment by arunoda** [comment]
> One possible solution we have here is to only call Blaze.render on the client. That way the SSR rendered version won'd include the login template, but that's really not too bad.

Yeah! It's a good solution.

**Comment by arunoda** [comment]
I think I'm going to close this and FR and no direct involvement with blaze. But our Blaze layout can built this once we've templates on the server.

**Comment by adamwong246** [comment]
I'm using blaze still- have not yet finished the long term refactor of blaze to react. However, I need to render some stuff on the server that uses neither react nor blaze. We render the sitemap.xml and the robots.txt on the server now. In order to upgrade from ironRouter to flowRouter, I need SSR.

I know this version does not intend, as of right now, to support blaze on the server. But is it possible to get SSR without blaze, and at the same time, blaze rendering on the client?
