### ISSUE TITLE
scroll to top on new route

### ISSUE THREAD

**Issue by buduguru** [meteorhacks/flow-router#223]
I'd like to implement scroll to top behavior when going to a new route.

It is important if, for example, we have list of articles, we scroll down the list and then if we open an article the window stays at the same position as it was on the list page, so reader starts to read not from the start but from the middle of the article.

What is the best practice to do it with flow-router?

**Comment by arunoda** [comment]
Yep. I've did something for that also.
You the Triggers.

**Comment by buduguru** [comment]
Thanks, will try them
