### ISSUE TITLE
A helper similar to iron:router pathFor

### ISSUE THREAD

**Issue by orlaqp** [meteorhacks/flow-router#224]
Great job with Flow Router and Layout!

I found the iron:router's helper pathFor very useful and I was wondering if you can add something similar to flow-router. In my project I added a helper like this:

```coffeescript
UI.registerHelper 'pathFor', (route, params, queryParams) ->
   FlowRouter.path(route, params, queryParams)

```

**Comment by arunoda** [comment]
Check this: https://atmospherejs.com/arillo/flow-router-helpers

**Comment by orlaqp** [comment]
Awesome thanks!
