### ISSUE TITLE
FlowRouter.path params and queryParams as strings?

### ISSUE THREAD

**Issue by rclai** [meteorhacks/flow-router#227]
```
FlowRouter.path(pathDef, params, queryParams);
```

For `params` and `queryParams`, are we able to pass strings to them, or do they have to be objects? If they have to objects, are you able to give the ability to pass strings?

For example:

```js
// For this route definition
FlowRouter.route('/path/:id1/:id2', { name: 'myRouteName', ... });

// Get path like this
FlowRouter.path('myRouteName', '1234/asdf', 'foo=bar&bar=baz')
```

**Comment by arunoda** [comment]
I think if you've them, you don't need to use path all. Simply concat them. :)

We mostly don't accept different types of arguments to path and most of our apis. It makes APIs hard to use and maintain.

**Comment by rclai** [comment]
I forgot why I asked this :laughing:. I will get back to you.
