### ISSUE TITLE
[Question] Become ready before the global subscriptions's ready. Is it design decision?

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-router#23]
`FlowRouter.ready()` gives `true` before the global subscriptions became ready.

**Comment by arunoda** [comment]
If so, that's a bug.
Could you share some code with me. I can look at it.

**Comment by delgermurun** [comment]
Okay. Gimme a moment.

**Comment by delgermurun** [comment]
check this out https://github.com/delgermurun/flow-router-demo.

If you go to `http://localhost:3000/blog/dfasdf` and debug it, it gives below:
```js
FlowRouter.ready("myCourses")
false
FlowRouter.ready("myPost")
true
FlowRouter.ready()
true
```

**Comment by arunoda** [comment]
I think I know the issue.
We handle global subs via another route located at `this._globalRoute`

In the [.ready](https://github.com/meteorhacks/flow-router/blob/master/client/router.js#L174) logic, we need to check that as well.
But, somehow we missed it.

I can work on this sometimes later today or tomorrow.
I'm happy, If you can work on this and send a PR with some tests.

**Comment by delgermurun** [comment]
Yeah, I looked through code and can't find code that checking global subscriptions. So I tested it :).

I'm happy to take a shot at it. Please wait for me :D.

**Comment by arunoda** [comment]
ha ha. Sure :D
