### ISSUE TITLE
FlowRouter.route must start with `/`

### ISSUE THREAD

**Issue by Kestanous** [meteorhacks/flow-router#26]
I spent a little while trying to debug this:
```js
FlowRouter.route('/unit/:unitId') //works
FlowRouter.route('unit/:unitId') //does not work and does not throw an error
```

If the route does not start with a forward slash it does not work. If this is the intended behavior can we get an error? Or is this supported in a way that I am not thinking of?

**Comment by arunoda** [comment]
Route should start with `/`, otherwise if might change the current path. 
But I rather like to throw an error on the case. 
Could you send me a PR with a test case.

I'd like it.

**Comment by Kestanous** [comment]
@arunoda I am about to head out for my weekend, will be AFK. I can do on Monday, if you have not gotten to it.

**Comment by arunoda** [comment]
Great.

**Comment by arunoda** [comment]
Hope we can close this.
