### ISSUE TITLE
How does "safeToRun" works?

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-router#27]
I call `Session.get` inside my `.subscriptions` route. It works without any error and I didn't notice any change.

By reading source code, I think it's purpose to avoid using reactive data in `.subscriptions`.

**Comment by arunoda** [comment]
An error gets thrown when the when it changed reactively.

**Comment by delgermurun** [comment]
oh I see.

I'm curios about what is the reason behind this decision :D?

**Comment by arunoda** [comment]
We don't allow any kind of reactive stuff run inside the router. If so, you
are doing something wrong.
There'll be another way to do it for sure.
This is made to avoid re-renders.

**Comment by delgermurun** [comment]
Yeah that makes a lot of sense to me. Now I really understand the this router's purpose.
I definitely need to really deeply understand tracker.

Thanks a lot.

**Comment by arunoda** [comment]
No problem.
