### ISSUE TITLE
Problem with publication ready status

### ISSUE THREAD

**Issue by ciwolsey** [meteorhacks/flow-router#28]
So I thought I would give your router a quick try and here's what I did:

https://github.com/ciwolsey/flow-router-problem

When visiting /posts all I get is:

Are posts ready? false
Yeah! We are on the posts!

Looks like the subscription status isn't updating reactively. Not sure why. Maybe it's something I'm doing wrong.

**Comment by arunoda** [comment]
You need to visit /post route to start that subscriptions. If you are not
in a route, we don't initiate global subs.

**Comment by ciwolsey** [comment]
I am visiting /posts .. thats why im getting output from console.log("Yeah! We are in the posts!");

**Comment by arunoda** [comment]
Okay. Then I will give this a shot.

**Comment by arunoda** [comment]
Check now. 
Yes. It had an issue and I fixed it with the latest release. (1.0.2)

The issue was, you were starting the tacker before route getting started.
So, we need to make sure, this re-run for every route change. Just did it.

**Comment by ciwolsey** [comment]
Yeah I just tried with the changes and it works well. Good job :)

**Comment by arunoda** [comment]
Great.

**Comment by arunoda** [comment]
Hope we can close this.
