### ISSUE TITLE
Naming route

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-router#30]
How about naming route?

```js
FlowRouter.route('/blog/:postId', {
    name: 'blogDetail',
    action: function(params) {
        console.log("Yeah! We are on the post:", params.postId);
    }
});
```
use like this:
```
FlowRouter.go('blogDetail', params);
FlowRouter.path('blogDetail', params);
```

We can achieve it by other way. Using something like `name => path` mapping in project. But I think it's nice to have builtin.

**Comment by arunoda** [comment]
We don't have it. It's by design. I believe it's confusing.

If needed you may can extend the router. But it's not part of the core.

**Comment by delgermurun** [comment]
Okay. Thanks for response.
