### ISSUE TITLE
Difference with IronRouter?

### ISSUE THREAD

**Issue by orefalo** [meteorhacks/flow-router#31]
The README should mention differences/benefits to iron-router. Why should I use flow router to begin with?  It is because of the flow-components architecture? is it just because it lightweight.

**Comment by arunoda** [comment]
No it's not with Flow Components and etc. This router only does routing and subscription registration. It does not wait for subs to be completed and re-run parts inside the router for any reason.

And it does not do rendering. So, you can technically use anything for view. Either templates, flow-components or React.

**Comment by dcworldwide** [comment]
Most of us with have similar questions to @orefalo. I think to save time and convince people to try it out... it would be great if the read me included something like a SWOT analysis table comparing IR and Flow Router. As a community we need this kind of transparency to make decisions.

**Comment by orefalo** [comment]
Indeed a good suggestion.

**Comment by jesseflorig** [comment]
@orefalo @dcworldwide +1

**Comment by arunoda** [comment]
Okay. Check docs: https://github.com/meteorhacks/flow-router#difference-with-iron-router

I've added a new section talking about the difference.

**Comment by orefalo** [comment]
Tks closing

**Comment by sayawan** [comment]
Easier to integrate with Famo.us , too.. than Iron Router :)

**Comment by dcworldwide** [comment]
Thanks Arunoda
