### ISSUE TITLE
QueryString vs QueryParams

### ISSUE THREAD

**Issue by ccorcos** [meteorhacks/flow-router#32]
I'm a little confused int he docs here:

https://github.com/meteorhacks/flow-router#flowrouterpathpathdef-params-querystring

**Comment by arunoda** [comment]
It should be queryParams. That's an issue in docs.
Would you mind sending a PR :)

Thanks.

**Comment by ccorcos** [comment]
https://github.com/meteorhacks/flow-router/pull/33
