### ISSUE TITLE
Simplify even more?

### ISSUE THREAD

**Issue by steph643** [meteorhacks/flow-router#34]
Having used Iron Router in the past 12 months, I dreamed about a simpler client-only router package. Here it is, thanks a lot!

In my dream, the new router was decoupled from template rendering. You did it!

In my dream, the new router was decoupled from subscription management. Is there a reason you didn't go this far? What would be the difference between:

    FlowRouter.route('/blog/:postId', {
        subscriptions: function(params, queryParams) {
            this.register('myPost', Meteor.subscribe('blogPost', params.postId));
        }
        ...
    });

and:

    FlowRouter.route('/blog/:postId', {
        action: function(params, queryParams) {
            this.register('myPost', Meteor.subscribe('blogPost', params.postId));
            ...
        }
    });

and finally:

    FlowRouter.route('/blog/:postId', {});
    Tracker.autorun(function() {
        Meteor.subscribe('blogPost', FlowRouter.getParam('postId'));
    });

?

In my dream, the new router would even have no `action` function. Why not just have the following?:

    FlowRouter.route('/blog/:postId');
    Tracker.autorun(function() {
        // Use the FlowRouter API the way I want
        ...
    });

**Comment by arunoda** [comment]
You should not use `this.register` inside the action. I you can that's a bug in Flow Router.

There is a reason for that we've a subscriptions in the router. 

* We believe subscriptions are aligned to a route most of the time. 
* For fast-render we need to run subscriptions on the server

That's why we have something like this.
But, we don't need to wait for subscriptions. That's why we only register it. Later you can check for the status.

**Comment by steph643** [comment]
Thanks @arunoda, understood.

My feeling is that maybe there is a simpler way to use your package that what is explained in the doc (for those who don't use fast-render and don't attach subscriptions to routes). I'll try to write an alternate manual if I have time.

Regarding the `ready` API, since I never attach subscriptions to a route, I use [Template.subscriptionsReady](https://github.com/meteor/meteor/blob/devel/History.md#blaze) instead.

**Comment by arunoda** [comment]
You need to have action method for the route. Otherwise you need to do some logic to pick the route and do the rendering.

**Comment by arunoda** [comment]
Yes. You can leave it alone. Both subscription and action are optional. May
be I can add it to docs.

**Comment by arunoda** [comment]
Yeah. I am quite happy to add a link to that manual on the read me.

**Comment by dandv** [comment]
I was going to ask something similar: since you can run any code in `subscriptions`, you can run rendering as well. Then what is the point of `action`?

```js
FlowRouter.route('/blog/:postId', {
    subscriptions: function(params, queryParams) {
        this.register('myPost', Meteor.subscribe('blogPost', params.postId));
        FlowLayout.render('componentLayout', {content: ...});
    }
    ...
});
```

I'm new to Flow-Router, so please pardon my ignorance :)

**Comment by arunoda** [comment]
subscriptions is different. I runs inside a autorun for managing
subscriptions (auto unsub.)
It also runs on the server.

Actions is a simply a function.
