### ISSUE TITLE
Best pattern to handle subscription updates after login & logout events 

### ISSUE THREAD

**Issue by christianvoigt** [meteorhacks/flow-router#35]
Hi, thanks for your work! 
I would like to try out flow router in my application, but after reading the documentation it is still not completely clear to me, what to do if a user logs in, logs out (and maybe logs in as a different user after that). In iron router, the page reloaded "all by itself" if one used Meteor.user() in the route action or in waitOn. I have some user-specific settings that I use for some subscriptions. If a user logs in, these subscriptions have to be updated. Do I have to use an autorun somewhere in my application code to check for that and then reload the page? Or is there a better way to do that?

**Comment by arunoda** [comment]
If a user logs out, there is no way to re-run the route automatically. We did purposely. If you need to do it with a autorun outside the router. In that case, you know exactly what you are doing. 

You don't need to re-run the after user logs-in and logs-out. Meteor will automatically change the data after the event.

**Comment by christianvoigt** [comment]
Ok, so in the autorun I would stop the subscriptions of the router and resubscribe for the same subscriptions with the new user data? Or would you recommend a complete reload of the page? Thanks for your fast help!

**Comment by christianvoigt** [comment]
Maybe to clarify: I would like to use FastRender, so I have to subscribe first in the Router. I can not completely mangage my subscriptions outside of FlowRouter.

**Comment by arunoda** [comment]
You didn't get my suggestion.
You don't need to manage subscriptions out side of the router.

Then simply reload the route. 
(Currently we don't have an API to reload the route. But you can append a [queryString](https://github.com/meteorhacks/flow-router#flowroutersetqueryparamsnewqueryparams) and it'll do the trick).

I bet you don't need to do this anyway. Try to think a bit. You could do it without loading or doing anything special. Think about this:

> You don't need to re-run the after user logs-in and logs-out. Meteor will automatically change subscription data after logout or login.

**Comment by christianvoigt** [comment]
thanks again, I got it now. Just didn't know that active subscriptions are automatically rerun after login/logout.

**Comment by arunoda** [comment]
Okay. great.
