### ISSUE TITLE
Using reactive value in middlewares

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-router#37]
I have login required middleware something like it:
```js
function requiredLogin(path, next) {
  var redirectPath = (!Meteor.userId())? "/sign-in" : null;
  next(redirectPath);
}
```

Since `Meteor.userId()` reactive, when I go to login required router, redirected to `/sign-in`. Even when I logged in. How did you solve this kind of issue? Do I have to use fast-render?

It's annoying especially in development. Because on every hot code push reload, it redirects to `sign-in`.

**Comment by arunoda** [comment]
Yes. We handle this using fast-render. I can't imagine some other ways to do this in the route level.

**Comment by delgermurun** [comment]
Okay. Thanks.
