### ISSUE TITLE
Redirect to login after logging out

### ISSUE THREAD

**Issue by bensmeets** [meteorhacks/flow-router#38]
Feels like a total noobie question, but trying flow-router out instead of IR (hopes it gives a little bit less overhead-feeling). In the IR situation, I had before-hooks, that checked if the user is logged in. After logging out (e.g. Meteor.logout() in console), the router reactively goes to the login page.

This doesn't seem to work in Flow Router. As far as I can tell, the middlewares aren't called when logging out. What is the correct way to do this in FR?

Cheers.

**Comment by arunoda** [comment]
You need to run a `Tracker.autorun` somewhere else watching for logging state of the user. Then with the state, you can call `FlowRouter.go()`

Some related discusstion: https://github.com/meteorhacks/flow-router/issues/35

**Comment by bensmeets** [comment]
Got it, tnx. Smooth like butter.

**Comment by arunoda** [comment]
Nice.

**Comment by arunoda** [comment]
Shall we close the issue.

**Comment by zimme** [comment]
Just and FYI

I'm gonna look into supporting flow-router in my `zimme:iron-router-auth` package which I will rename if I can add support for flow-router. There's a possibility it will be a separate package.

But it will take some time so don't hold your breath :smirk:

**Comment by arunoda** [comment]
Great :)

**Comment by zimt28** [comment]
@zimme Amazing!

**Comment by charlesdeb** [comment]
I have been struggling with Meteor.logout() and FlowRouter. I am trying to follow all of the suggestions in the Flow-Router guide, and also the suggestion above to put a `FlowRouter.go` in a `Tracker.autorun` that watches for change of log-in state and redirect to another page. It all seems to work fine and I do eventually get to this new page on log-out.

However, between pressing 'logout' and getting to the new page, there are heaps of errors in the console. From debugging console.log statements, I can see that after pressing the logout button and triggering `Meter.logout()`, it looks like before the `Tracker.autorun` that would redirect to a new page runs, the existing page starts to re-render - and that causes the errors.

I can put guard code in to prevent these errors, but I don't understand why the existing page should be trying to re-render.
