### ISSUE TITLE
Is there a "user accounts" package supporting flow-router?

### ISSUE THREAD

**Issue by steph643** [meteorhacks/flow-router#40]
Just to let you know that the only thing that prevents me from switching to flow-router is that I use the [useraccounts](http://useraccounts.meteor.com/) package. I hope they will allow soon to use flow-router (see https://github.com/meteor-useraccounts/core/issues/308).

**Comment by dcworldwide** [comment]
:+1:

**Comment by 3even** [comment]
Looking forward to this aswell.

**Comment by boustanihani** [comment]
:+1:

**Comment by rclai** [comment]
For now you can do [this](https://github.com/meteor-useraccounts/core/blob/master/Guide.md#flow-router-integration).

**Comment by arunoda** [comment]
Closing this since, there are some on going stuff on this.
