### ISSUE TITLE
Hooks

### ISSUE THREAD

**Issue by gabrielalmeida** [meteorhacks/flow-router#41]
As there are no hooks available, is there a way to replicate  this behavior below?

```
Router.onStop(function () {
  IonScrollPositions[Router.current().route.getName()] = $('.overflow-scroll').scrollTop();
});
```

I mean, is there an easy way to run some sort of code right before a route change? Middlewares aren't able to do that because it runs only at the initialization step and it's already lost previous route access.

Thanks

**Comment by arunoda** [comment]
I can see the usefulness. Let's see what we can do.

**Comment by zimt28** [comment]
It would really be cool to have hooks and more powerful middleware (see #45, language rewrites).
Even though Flow doesn't come with a loading page, I like them in some cases. It's possible to do this without any problems:
```javascript
FlowRouter.route('/post', {
  subscriptions: function() {
    this.register('post', Meteor.subscribe('post'));
  },
  action: function() {
    Tracker.autorun(function(c) {
      if (!FlowRouter.subsReady('post')) {
        FlowLayout.render('layout1', { main: 'loading' });
        return;
      }
      FlowLayout.render('layout1', { main: 'singlePost' });
      c.stop();
    });
  }
});
```
But it would be cool if we could just register ad hook/ plugin for those situation where we'd have to repeat so much code. I understand that we don't want to build a second iron:router here, but it's good to think about a minimal api which lets you do as much as possible.

**Comment by arunoda** [comment]
Let's carry over the discussion here: https://github.com/meteorhacks/flow-router/pull/59
