### ISSUE TITLE
page.js context?

### ISSUE THREAD

**Issue by dcworldwide** [meteorhacks/flow-router#42]
Is it possible to get access to the page.js context? 

I'm curious about using page.js's context to save route specific state for my application.

**Comment by arunoda** [comment]
You can get it from `FlowRouter.current().context`

**Comment by arunoda** [comment]
Hope we can close this.

**Comment by dcworldwide** [comment]
Thanks Arunoda, was helpful for me.

**Comment by arunoda** [comment]
May be we want add this to the README.
