### ISSUE TITLE
Hash support?

### ISSUE THREAD

**Issue by dcworldwide** [meteorhacks/flow-router#43]
Does flow router support url hashes? 

I'm considering the use of hashes as a way to control the UI (i.e. show/hide modals) of a single page (single route). This is a pattern that Iron Router does a poor job of explaining but i believe is a very common pattern. Thanks

**Comment by arunoda** [comment]
I'm not quite sure it's working on not. Anyway page.js seems to support it.
So, do flow-router.
https://github.com/visionmedia/page.js/issues/112

**Comment by hpx7** [comment]
Looks like there is no way to get/set hashes though. Something like `FlowRouter.getHash()` and `FlowRouter.setHash()`.

**Comment by frozeman** [comment]
page.js has hashing support: https://github.com/visionmedia/page.js#pageoptions

But how do i enable it in flow router? How do i access the page.js object?

**Comment by benjamin79** [comment]
FlowRouter.current().context.hash

**Comment by arunoda** [comment]
There is a PR for this as well. Which is nice I will merge it soon.

**Comment by arunoda** [comment]
There is a PR to add hash support to flow router. But, it get conflicts when we add IE9 support. See my original comment: https://github.com/meteorhacks/flow-router/pull/110#issuecomment-102779714

We can of course add an API to get the hash reactively. But, I'm quite not sure about setting it. 

@dcworldwide What's your use case to use hash? Can't you deal with it query params?

**Comment by dcworldwide** [comment]
@arunoda My use case is that i have a complex single page application (single route) with multiple states. I need to store each state in the browser history (i.e using a hash). My code applies transitions to move between states. When i share hashed urls with other users, i expect that when the user opens the url that the the hash is used to transition the page to the appropriate state. A state could be as simple as a scroll position, or as complex as an expand grid card / modal. I guess params would work for me?

**Comment by arunoda** [comment]
Hmm. I see.

**Comment by arunoda** [comment]
Closing this for now. 
See here for the reasoning. https://github.com/meteorhacks/flow-router/pull/110#issuecomment-111402565

**Comment by frozeman** [comment]
Thanks. Thats what i would need. hash support for routing.

Iron Router seem to first try to resolve using html5 push state and then falls back to hash, ideally we can set the hash option somewhere before any of the logic starts..

**Comment by frozeman** [comment]
@arunoda how do i access the page.js object to enable hasbang urls, instead of html push state?
https://github.com/visionmedia/page.js#pageoptions

This is very important to make single plage apps also work on the `file://` protocol, e.g. for desktop based apps like [electron](https://github.com/atom/electron/issues). Where the the app should work in a normal browser, but also within the desktop app container (where its served as index html using [meteor-build-client](https://github.com/frozeman/meteor-build-client))

It would be awesome if you can expose that page.js objecty so i can enable this!

**Comment by frozeman** [comment]
The error you get when using the file protocol is:
```
Uncaught SecurityError: Failed to execute 'replaceState' on 'History': A history state object with URL 'file:///Users/frozeman/Sites/_ethereum/meteor-dapp-wallet/build/index.html' cannot be created in a document with origin 'null'.
```

**Comment by frozeman** [comment]
Actually simply adding hashing support is not enough, as on file protocol the `.replaceState` will still throw an error. So it seems besides disabling web security there is no solution for this.

**Comment by fvpDev** [comment]
Any news on this?
