### ISSUE TITLE
Current path

### ISSUE THREAD

**Issue by michalvalasek** [meteorhacks/flow-router#44]
Hello,

I have a menu in my app and I want to highlight the current link in it. The `FlowRouter.current()` isn't reactive and you're discouraging the use of `FlowRouter.currentReactive()`. I'm wondering what's the correct way of implementing this "feature" with FlowRouter?

**Comment by arunoda** [comment]
Okay. If that's just a single helper and you are not using anything else
inside it, use reactiveCurrent()

Idea is this. When you are using it, you need to know how you are using it.
That's why make the distinction.

**Comment by michalvalasek** [comment]
Thank you very much for the prompt answer and explanation!

**Comment by VladShcherbin** [comment]
probably we can specify this case in readme as many users may want to have an **active** class helper
