### ISSUE TITLE
From Iron to Flow Guide

### ISSUE THREAD

**Issue by zimt28** [meteorhacks/flow-router#45]
Is there a good strategy on migrating a page using iron:router to flow router? I'm just having problems with the new iron:router and flow router seems really predictable. I have to admit that I've just looked ad flow router for the first time and it might be so easy, that you don't need a guide or good advise for migrating it, but it might be a question other people have as well. So maybe a small migration guide or a comment in the docs might be helpful!

**Comment by arunoda** [comment]
Good Idea.
I'll work on something. 
But, I'm not a IR specialist. 
If someone can show me what are things you do with IR, then I can show some possible ways to do with FR.

Can you start list of the stuff you do with IR?

**Comment by zimt28** [comment]
Basic things in most cases. Authentication, authorization, managing subscriptions. And I'm using it for [language management](https://github.com/yoolab/iron-router-i18n). So it's basically fetching the lang from the url (first segment) or adding it, if there's no language set. It's also possible to give routes different names for different language. So `/en/about-us` and /de/ueber-uns` are the same route.

**Comment by zimt28** [comment]
I just had a look at the readme and I don't see how that could be done. The middleware seems really basic, so it can redirect, but not rewrite routes, can it?

**Comment by martinopic** [comment]
I'm the author [Iron Router i18](https://github.com/yoolab/iron-router-i18n). I was already thinking of providing the same functionality to Flowrouter (I'm very interested in it), follow https://github.com/yoolab/iron-router-i18n/issues/47 for news about it.

**Comment by arunoda** [comment]
@martinopic Nice.
