### ISSUE TITLE
how to  get the custom property in router?

### ISSUE THREAD

**Issue by yuomtheara** [meteorhacks/flow-router#47]
I would like to set page header on router property like this:
```
FlowRouter.route('/blog/:postId', {
    pageHeader: {title: 'My Title', icon: 'home'},
    .........................................
});
```
how to get the custom property?
because i would like to generate `page header`, `breadcrumbs`...

**Comment by arunoda** [comment]
This is not handle in the router. You need to do it in the template/layout
layer.
Or may be use middlewares.

We never want to give native support for these kind a apis in he router.

**Comment by yuomtheara** [comment]
Very thanks for your reply.
