### ISSUE TITLE
Setting query params on path with optional last param causes build up of question marks

### ISSUE THREAD

**Issue by elidoran** [meteorhacks/flow-router#48]
Configured path in FlowRouter:

    /app/data/:cat?

After first visit to that route the browser location shows: 

    /app/data

After setting query params via console {priority: '1', status='open'} the browser location is:

    /app/data/??priority=1&status=open

And FlowRouter.getQueryParam("priority") will *not* return value '1'.

Repeat the setQueryParams again (with same values), and it is now:

    /app/data/???priority=1&status=open&priority=1

Each subsequent setQueryParams adds another question mark whether I use new query params or the same ones. The question marks just build up.

When I navigate to another route they are cleared out.

When I remove the optional parameter from the route path this issue goes away.

When it's showing `/app/data` and I set the param with setParams({cat:'blah'}) the browser location shows:

    /app/data/blah?

So, an optional last param causes a question mark to show.
And, setting query params on it causes a build up of question marks.

**Comment by elidoran** [comment]
It's a problem in the FlowRouter.path function call. If I run this in the console the extra question mark shows:

    FlowRouter.path('/app/data/:cat?', {}, {q:'one', s:'two'});  =>
    /app/data/??q=one&s=two

    FlowRouter.path('/app/data/:cat?', {cat: 'test'}, {q:'one', s:'two'});  =>
    /app/data/test??q=one&s=two

I'm trying for an optional parameter like [path-to-regexp](https://github.com/pillarjs/path-to-regexp#optional) explains.

I added some tests to flow-router which show this issue. I'm working on a pull request for the tests before looking for a fix.

**Comment by elidoran** [comment]
Posted a pull request with both tests for this and a fix.

**Comment by arunoda** [comment]
Thanks.
Fixed with #50
