### ISSUE TITLE
Question: Cordova Support

### ISSUE THREAD

**Issue by boustanihani** [meteorhacks/flow-router#49]
Does Flow-Router has Cordova support?

**Comment by arunoda** [comment]
We are using page.js behind the scene. It should work.
But we didn't test it yet!

**Comment by boustanihani** [comment]
I have been testing cordova and everything is working fine so I guess we can close this :)

**Comment by amannigam** [comment]
My flow router is not really working with cordova. It works fine on the desktop but not on android. Anyone facing this?

**Comment by jessejamesrich** [comment]
I'm having a similar problem to amannigam.
