### ISSUE TITLE
Best way to check permissions

### ISSUE THREAD

**Issue by Goluis** [meteorhacks/flow-router#51]
I'm finishing to spend my application from Iron-router to Flow-layout and am very happy with the result. the only thing I'm missing now is to check the permissions of a user and see if he can enter the route

on iron router I was doing something like this
```js
Router.onBeforeAction(function () {
  var user = Meteor.user();
  // check
});
```
and flow-router would be something like this
```js
FlowRouter.middleware(function () {
  Tracker.autorun(function () {
    if (FlowRouter.subsReady()) {
      var user = Meteor.user();
      // check
    }
  })
});
```
I'm not sure if this is the right way to use flow-router so I would ask if there is a better way

**Comment by arunoda** [comment]
In flow-router router is not reactive and it does not wait. So, running a tracker inside this is possible, but does not give you results. There are two ways to address this issue:

1) Fast Render
When you added fast-render all the data is there, when you loaded the page.
So, you can simply check `Meteor.user();` 

2) Check outside the router
As with the reactive changes, create a new tracker somewhere in your code.
Check for the changes and change routes with `FlowRouter.go()`.

These are some of the ways to handle this problem.

**Comment by elidoran** [comment]
I use a very generic route path which uses parameters to represent all my paths (Thank you FlowRouter+FlowLayout). So, I needed a way to apply the requireLogin middleware to all routes except the account entry stuff (login/create/forgot password). Iron Router has the 'except' (and 'only') filter for middleware (onBeforeAction).

I use fast-render and a middleware similar to this to redirect unless logged in or already going to an entry route (similar because I use CoffeeScript and I hand translated these to JavaScript). Also, I included commented versions for using a query parameter instead of the Session.

```javascript
var entryPath = /^\/entry/
function requireLogin(path, next) {
  if( !(Meteor.userId() || entryPath.test(path)) ) {
    Session.set('returnAfterLogin', path);
    var whereTo = '/entry/login';
    // or store return path as a query parameter
    //var whereTo = '/entry/login?returnTo=' + path 
  }
  next(whereTo);
};
``` 

In my callback after a successful login in I do:

```javascript
var returnTo = Session.get('returnAfterLogin') || '/';
// or if it's a query parameter
//var returnTo = FlowRouter.getQueryParam('returnTo') || '/';
FlowRouter.go(returnTo);
```

To watch for a logout I do:

```javascript
Tracker.autorun(function() {
   if( ! Meteor.userId()) { // reactive
      var path = FlowRouter.current().path;  // not reactive
      if (path) { // when user enters app the path is undefined
          Session.set('returnAfterLogin', path);
          whereTo = "/entry/login";
          // or store return path as a query parameter
          //whereTo = "/entry/login?returnTo=#{path}"
          FlowRouter.go(whereTo);     
      }
   }
});
```

**Comment by arunoda** [comment]
Thanks @elidoran for showing the example for us.
So, it seems like then we need to have named routes to have the functionality you mention.

Let's see what we can do about it.

**Comment by elidoran** [comment]
At first I missed named routes a lot. After thinking about routes differently I've changed how I specify routes making heavy use of the specificity we get with FlowRouter's getParam. I'll add more info to the issue #39 about named routes.

**Comment by arunoda** [comment]
Let's carry over the discussion on except here: https://github.com/meteorhacks/flow-router/pull/59
