### ISSUE TITLE
Why does flow router change the url?

### ISSUE THREAD

**Issue by WooGenius** [meteorhacks/flow-router#52]
Hello. Now I'm applying flow router instead of iron router on our service. It's pretty good and well working. Thanks for implementing beautiful router.

I have a question. Why does flow router change url? is this bug?
When i access below page by url, Flow router changes
* `/foo?` -> `/foo`
* `/foo?a=b%26c&d=e` -> `/foo?a=b&c&d=e`

Thanks in advance.

**Comment by arunoda** [comment]
We are using page.js behind the scene. 
May be that's something they are doing.
Anyway, I'd like to investigate why?

**Comment by WooGenius** [comment]
Actually I updated page.js to current version on my branch. It's working well.
Do you mind if i make PR of it?

**Comment by arunoda** [comment]
Okay sure. Send me that.
