### ISSUE TITLE
Pass FlowRouter.current() to both middleware and action ?

### ISSUE THREAD

**Issue by elidoran** [meteorhacks/flow-router#53]
Right now middleware gets path only and action gets params and queryParams. 

I'm thinking it makes sense to instead pass the 'current' object to both of those. We can get all three objects from that (path, params, queryParams).

I noticed I'm doing `FlowRouter.current()` in `action()` to get the whole path. I'm sure it seems like an action() will already know its path, but, with params and queryParams involved it changes.

Also, in middleware I use `FlowRouter.getParam` because it only has path.

It seems it would be consistent to always provide the current object (`FlowRouter.current()`).

What are your thoughts?

**Comment by arunoda** [comment]
I prefer to have the syntax in this way.
It's very clear in that way. (just my idea)

But we can have params and queryParams in the middleware.

**Comment by elidoran** [comment]
I inspected the contents of the values and see the params object actually has the path in it with the key `0`. And, the query params are in it as well with key `query`. It seems unlikely anyone will use the name `query` for a parameter and cause a name conflict. It also looks a little odd to have path in there accessed with `0`, but, it's nice it's in there (I can drop my FlowRouter.current().path call). 

I can easily workaround this, no biggie. Seems odd like routes don't care about their path and middleware doesn't care about params/queryParams.

To ensure I was clear in my above rambling, I was thinking of this:

```coffeescript
someMiddleware = (currentRoute, next) ->
  # currentRoute has { path, params, queryParams }
  # can do whatever with any of those three...
  next()

FlowRouter.route '/some/path', 
  action: (currentRoute) ->
    # same stuff in this currentRoute object
```

That looks clear to me (consistent and full featured). Up to you :)

If you do add params/queryParams to middleware, would you make the `next` the first argument because it's always used, and that allows path/params/queryParams to be optional? Or, what argument order would you use?

**Comment by arunoda** [comment]
Okay I got it.
May be middlewares can have 1.0 next before others.
Anyway, I'm thinking about the backward compatibility. Any ideas.

**Comment by elidoran** [comment]
That's a good point, and a tough one. Perhaps it's something to put off for a version 2.0.

In version 1+ add a new property name for middleware which uses the new parameters, such as `beforeAction` and `beforeActions`. Then in version 2+ drop support for the `middleware / middlewares` properties. I think you likely chose the names middleware(s) because you prefer them though.

I don't see how to alter the `action` in a similar way, but, it's the one which actually receives all the values; it's just path is hidden inside the `params` object as:

```coffeescript
FlowRouter.route '/some/thing/:id',
  action: (params, queryParams) ->
    path = params['0']  # same as: FlowRouter.current().path
```

As is, I'm applying regular expressions to the `path` in middleware instead of getting params/queryParams info. And, I'm getting the path from `params['0']` in `action`.

Also, we can call FlowRouter.current() in either place to get the missing info.

**Comment by yvann** [comment]
+1, nice idea to access the (query)?params in the middlewares !

**Comment by arunoda** [comment]
Let's carry over the discussion here: https://github.com/meteorhacks/flow-router/pull/59
