### ISSUE TITLE
Page reload on route change

### ISSUE THREAD

**Issue by wI2L** [meteorhacks/flow-router#65]
Hello arunoda,

I'm trying to switch from IronRouter to FlowRouter. I am using FlowLayout aswell.
Here is my issue. Since there is no support for IronRouter `{{pathFor}}` functionnality like, yet, i am writing my links directly like this `<a href="/signin">Sign in</a>`

Problem is when i click on a link, the page reload completely. This looks strange for me because the layout is the same for the views, only the template change.

My layout looks like this:

```
<template name="externalFormLayout">
    <div id="external-form">
        {{> Template.dynamic template=main}}
    </div>
</template>
```

And the routes:

***signin***
```
FlowRouter.route('/signin', {
    action: function (params) {
        FlowLayout.render('externalFormLayout', {
            main: 'signinTemplate'
        });
    }
});
```

***signup***
```
FlowRouter.route('/signup', {
    action: function (params) {
        FlowLayout.render('externalFormLayout', {
            main: 'signupTemplate'
        });
    }
});
```

Is it a FlowRouter or a FlowLayout error?

Regards,

William

**Comment by wI2L** [comment]
Hi again.
Seems i was able to fix it quickly.
I just removed the package `manuelschoebel:ms-seo` and it work as expected now.

**Comment by MHerszak** [comment]
I have the exact same problem. My browser refreshes the page when I click on a link and I don't have manuelschoebel:ms-seo package installed. Any idea how to solve this? I am using BlazeLayout.render:

```javascript
FlowRouter.route('/pageTwo', {
    name: "pageTwo",
    action: function(params, queryParams) {
        BlazeLayout.render("mainLayout", {main: "pageTwo"});
    }
});
```
So when I click a link I am always ending up with a page refresh. Any help is appreciated. Thank you.

**Comment by arunoda** [comment]
@MHerszak hey I need a sample repo. May be it's better to create a new issue.

**Comment by MHerszak** [comment]
Unfortunately, I am not allowed to show the code. I tried something else and used iron:router.
```javascript
Router.route('/pageTwo', {
  name: "pageTwo",
  action: function(params, queryParams) {
    BlazeLayout.render("mainLayout", {main: "pageTwo"});
  }
});
```
It did the trick, now I am concerned to introduce conflicts when I use FlowRouter

**Comment by MHerszak** [comment]
@arunoda I am getting this error displayed: Oops, looks like there's no route on the client or the server for url: "http://localhost:3000/admin/settings." but this route is defined and gets rendered. So I see the page and the template but I get this error. Any idea?

**Comment by awei01** [comment]
@MHerszak: I ran into a similar issue and had to enable `hashbang` support. Perhaps it's the same thing? 

In some client file:
```
FlowRouter.wait();
Meteor.startup(function() {
	FlowRouter.initialize({ hashbang: true });
});
```

**Comment by stevenhornung** [comment]
@MHerszak were you able to solve this issue? I'm in the process of migrating from IR to FlowRouter and I'm seeing this same reload problem. I had manuelschoebel:ms-seo but I've removed that. I'm guessing this is probably another package conflict but I haven't been able to pin point it yet.

**Comment by MHerszak** [comment]
@awei01 and @stevenhornung .. I did reconsider and started with React from scratch. This far into the project, I must say it was the best decision to go with React and FlowRouter. Sorry that I can't be of more help.

**Comment by Orbyt** [comment]
I'm having this issue as well, using BlazeLayout. I'm using the demo code, and it reloads the page if I navigate to a new route

**Comment by hayk94** [comment]
Same issue. Are there any news on this?
