### ISSUE TITLE
Route aliases/forwarding.

### ISSUE THREAD

**Issue by trusktr** [meteorhacks/flow-router#72]
I've something like

```js
FlowRouter.route('/blaze', {
    action: function(params) {
        FlowRouter.go('/blaze-prototype');
    }
});
```

so `/blaze` forwards to `/blaze-prototype`, but the side effect is that pressing the back button in the browser causes the page to go back to `/blaze` which immediately forwards back to `/blaze-prototype`.

Is it possible to make the back button go back to the URL that was before `/blaze`? Or would I need to do this in the backend with meteorhacks:picker?

**Comment by trusktr** [comment]
But if I use meteorhacks:picker then that only works for the initial request, but what about if the user visits the URL programmatically inside the app?

**Comment by arunoda** [comment]
Try using FlowRouter.redirect() instead of go.

**Comment by trusktr** [comment]
Oh, ok, cool! It wasn't mentioned in the README.
