### ISSUE TITLE
Seo title and description

### ISSUE THREAD

**Issue by VladShcherbin** [meteorhacks/flow-router#73]
Guys, please share, what is your preferred way to set the title and description of the page?

Are you doing it in router or in Template. What about some dynamic items as blog posts - since router does not wait for data -> how you set title from the blog document.

Thanks

**Comment by arunoda** [comment]
You can change titles outside the router and when rendering it via phantomJS it'll detect it correctly.
You can also use middleware for static titles (which does not need to access the data)

**Comment by dcusan** [comment]
I just had another question regarding this and didn't want to open a new issue?
How can I do this with `kadira:flow-router-ssr@=3.7.3` both for server and client? An example would help a lot, couldn't find any. Thanks! 

Am I correct in assuming there is no longer middelware?
