### ISSUE TITLE
query.js bug

### ISSUE THREAD

**Issue by delgermurun** [meteorhacks/flow-router#74]
`FlowRouter._qs.stringify({appId: 'new-i', hi: []});` returns `"appId=new-i&"`,

so `FlowRouter._qs.parse('appId=new-i&');` returns `{appId: "new-i", "": ""}`,

so `FlowRouter._qs.stringify({appId: "new-i", "": ""})` raising error.

I think `FlowRouter._qs.stringify({appId: 'new-i', hi: []});` should be `"appId=new-i"` and `FlowRouter._qs.parse('appId=new-i&');` should be `{appId: "new-i"}`

I reported bug on [page.js's repo](https://github.com/visionmedia/page.js/issues/248).

But I think we should remove empty string keys (and values) before set query params, whether `query.js` works correctly or not.

**Comment by delgermurun** [comment]
I've just found out that query.js [derived from](https://github.com/visionmedia/page.js#plugins) https://github.com/tj/node-querystring and it's deprecated. https://github.com/hapijs/qs is maintained repo.

I've not test it. But I hope, this issue had fixed on it.

@arunoda I think we should port to maintained version.

**Comment by arunoda** [comment]
Oh. Yes. We should. And we need to make a note on where we get it.

**Comment by arunoda** [comment]
See: #104 
Not we got the latest version.
