### ISSUE TITLE
FlowRouter.notfound should be camel case and defined in constructor

### ISSUE THREAD

**Issue by mikowals** [meteorhacks/flow-router#75]
I can make a pull request if you like.  It was just confusing when `.notFound` wasn't working and I expect a lot of people would make that mistake.

**Comment by arunoda** [comment]
Okay. Send me a PR.
And keep the old one as well (for backward compatibility, we can remove it when 2.x hits)

**Comment by delgermurun** [comment]
`Router.prototype._notfoundRoute` also should become `_notFoundRoute`.
