### ISSUE TITLE
Links not changing route

### ISSUE THREAD

**Issue by DEfusion** [meteorhacks/flow-router#81]
This may be my particular app, I've also got IronRouter in the app as it's a dependency of user accounts but I've disabled it with this `Router.options.autoStart = false` in my route file (otherwise I get the iron router instructions page).

Clicking links that match routes changes the URL but does not load the route, however calling `FlowRouter.go(...)` with the route does load the route as does the browser history back/forward button, whichever way the URL was changed. 

The confusing thing to me the browser history, e.g. click link A URL changes, route doesn't get loaded, click link B same result, press back button route A loads as expected.

**Comment by arunoda** [comment]
You can't use both IR and FR at once. That's the issue.
I hope both is trying to to update links.
