### ISSUE TITLE
Route reload support: FlowRouter.reload()

### ISSUE THREAD

**Issue by arunoda** [meteorhacks/flow-router#83]
This will simply re-run the route (including the middlewares, subscriptions and action)
When implementing this, we need to implement idempotent feature to the router. It will never change the route for due to path re-run.

We need to handle it on the pagejs level. But when called `reload()` we need to  re-run it.

### Implementation Details

* Simply rerun the router
* First, We need to re-run all the exit triggers for the current route
* Then, We need to re-run all the enter triggers for this route. 
* We need to call the action

> We may can use `this._invalidateTracker()` 
> But before that we may need to run exit triggers

**Comment by arunoda** [comment]
May be we can push this with #57

**Comment by arunoda** [comment]
I think we can have this.

**Comment by Firfi** [comment]
+1 for reload, i.e. there's use case when you can have some permissions checks in router middleware which depends on current user that can be changed independently.

**Comment by arunoda** [comment]
@delgermurun could you work on this feature too. Then I can focus on the Auth Manager #139 and do the 2.0 release.

**Comment by delgermurun** [comment]
@arunoda Of course, I can work on it.
