### ISSUE TITLE
API reactive getName

### ISSUE THREAD

**Issue by wI2L** [meteorhacks/flow-router#86]
Hi!

Since we have named route in this package, it would be great to have a reactive function that return the name of the current route.
Actually, i am using the `reactiveCurrent` to get the route name reactively with `FlowRouter.reactiveCurrent().route.name`.

What do you think ?

My usecase is simple, on a template, i've created a helper to reactively return the string `active` for a `<a>` tag in a menu based on the active route name.

**Comment by jhuenges** [comment]
You could use this existing solution:
https://atmospherejs.com/arillo/flow-router-helpers

**Comment by wI2L** [comment]
@jhuenges 

I could but this does not answer my issue.
The package you linked to me use `reactiveCurrent` internally:
https://github.com/arillo/meteor-flow-router-helpers/blob/master/client/helpers.coffee#L19

**Comment by gadicc** [comment]
Oh blah, I missed this in my search for "name".  See #105 (issue) and #106 (PR).  @wI2L / @arunoda, sorry, let's close this and track in the PR.

**Comment by wI2L** [comment]
@gadicc No proble, thank you for the PR. I'll follow until it's merged.
