### ISSUE TITLE
No data with flow-router without server side routes

### ISSUE THREAD

**Issue by wI2L** [meteorhacks/flow-router#88]
Subscriptions made with FlowRouter are not processed with FastRender.
Have to add server side routes to get it work.

https://github.com/meteorhacks/fast-render/issues/107

**Comment by arunoda** [comment]
noted.

**Comment by delgermurun** [comment]
@arunoda Is there something to relate my changes? If so please give me a hint, I want to help.

**Comment by arunoda** [comment]
Actually, I found the issue.
Something related to name change. I'm on the way to fix it.
Didn't check who caused the issue :)

**Comment by delgermurun** [comment]
okay :)

**Comment by arunoda** [comment]
@wI2L I published a new version. (1.4.2)
Check that.

**Comment by wI2L** [comment]
@arunoda 
This is perfect. Data is there without server side routes.
Thank you for your work and the quick fix. Duly appreciated.
Seems like we can close this issue.

**Comment by arunoda** [comment]
Great.

**Comment by delgermurun** [comment]
I'm the one who changed naming. Sorry about that guys.

**Comment by arunoda** [comment]
No problem. If we had tests for fast render, we didn't had this issue. I
added them with this. So, this is a good issue.

**Comment by petrometro** [comment]
I'm still getting this issue on version 1.7.0... 

Client (lib/router.js) : 

```
FlowRouter.route('/', {
	name : 'home',
	subscriptions : function(){
		console.log('sub called');
		this.register('baseSubs', Meteor.subscribe('baseSubs'));
	},
	action : function(){
		FlowLayout.render('homeLayout');
	}
});
```
Server (server/publications.js) : 
```
Meteor.publish('baseSubs', function(){
    // normal code, nothing special
});
```
The only data from FastRender is the user, which is all correct. However, if I add this to server/publications.js :+1: 
```
FastRender.route('/', function(){
    this.subscribe('baseSubs');
});
```
then everything works fine.
