### ISSUE TITLE
Access the name and params of previous route

### ISSUE THREAD

**Issue by miri-am** [meteorhacks/flow-router#89]
How to access the name and params of the previous route (the one that was just left)?

**Comment by wI2L** [comment]
You should consider using `Session` to store this informations between routes.

**Comment by miri-am** [comment]
But where to set/get the Session variable? If I set it in `action`or in `middlewares` (which I think is run before action), I cannot access the previous route in my template anymore. Don't you need something like Iron-Router's onStop hook?

**Comment by arunoda** [comment]
In the middleware, you can router.current() and save it to a global variable called last route. So, you can access it the next time.
We'll have something like after hooks in the next major version, which will be called after the user left from the route. Hope it helps.

**Comment by miri-am** [comment]
thanks. That helps!

**Comment by mquandalle** [comment]
@arunoda, is there still a way to get the previous path (either from a trigger or from the action)?

**Comment by mquandalle** [comment]
I guess one way would be to add a global trigger on exit:

```
let previousPath ;
FlowRouter.triggers.exit([({path}) => {
  previousPath = path
}]);
```

Is that the canonical form?

**Comment by faisalhasnain** [comment]
You can use triggers to set the last route visited as:
```
FlowRouter.triggers.exit(context => {
  Session.set('lastRoute', { name: context.route.name, params: context.params });
});
```
```
And where you need to compare with last route, do something like this:
const current = FlowRouter.current();
const last = Session.get('lastRoute');
if (current.route.name == last.name) {
}
```
