### ISSUE TITLE
API to disable routing

### ISSUE THREAD

**Issue by wI2L** [meteorhacks/flow-router#92]
Hello @arunoda 

I was thinking of a use case when the client loose the connection with the server.
In this case, like a lot of apps, i show a dimmer/absolute div to explain the problem, provide a reconnection button and a timer.

Anyway, this is not the problem. I was thinking of blocking the routing globally in my app when the client connection is lost to prevent from page reloading, or things like that.

I couldn't figure by myself a solution to achieve this with the actual implementation of flow-router. I'd like to hear you about this. Could it be a feasible feature for flow-router, or do you have any ideas about this problemtaic?

Best regards,

William

**Comment by arunoda** [comment]
Flow Router won't have such an API. May be someone can write a package for this.
