### ISSUE TITLE
Question: history.back()

### ISSUE THREAD

**Issue by boustanihani** [meteorhacks/flow-router#94]
Is there a recommended way for doing ```history.back()``` with flow-router?

Maybe also a recommended way for  clearing the history...

**Comment by Streemo** [comment]
Maybe you could keep track of the last N paths by pushing the most recent path string into a global array called `pathHistory` via global middleware and then do something similar to

```goBack = function(n){
    var length = pathHistory.length;
        FlowRouter.redirect(pathHistory[length-(n+1)])
}

clearHistory = function(){
  pathHistory = [];
}```

goBack(0) doesn't go back. goBack(1) goes back 1 path, ...
see https://github.com/meteorhacks/flow-router/issues/89

**Comment by boustanihani** [comment]
Thanks for your feedback, I hope the next major release will have an out-of-the-box solution for this :)

**Comment by Streemo** [comment]
The way I see it is that flow router is incredibly minimal and leaves that
functionality up to us to implement in whichever way we want, or not at all
if we don't need it. Flow router is supposed to be like that. If im not
mistaken, that was part of it's design.

**Comment by boustanihani** [comment]
I like the minimal design, but going back() is IMO basic routing functionality.

**Comment by arunoda** [comment]
history.back() works pretty well with flow router. I don't know there is a browser API to clear the history.

**Comment by arunoda** [comment]
I'm closing this now. If you are looking for something else. Let's discuss.

**Comment by patrickml** [comment]
@arunoda how would you go back to the previous route but ignoring the same route if it has query params.

Example : 

`route 1` : https://example.com/page1
`route 2` : https://example.com/page2
`route 3` : https://example.com/page2?tab=1
`route 4` : https://example.com/page2?tab=2

Now i want to go back to route 1 because it is the only page with a different path

**Comment by arunoda** [comment]
There is no built in functionality in FlowRouter for this. May be check this is what you need.
See: https://github.com/kadirahq/flow-router#flowrouterwithreplacestatefn

**Comment by DrZivil** [comment]
var route = FlowRouter.current();
if(backRoute.oldRoute){
	console.log('back', route.oldRoute.name);
	FlowRouter.go(route.oldRoute.name);
}else{
	FlowRouter.go('home');
}

this works pretty well for me so far...
