### ISSUE TITLE
Uncaught URIError: URI malformed

### ISSUE THREAD

**Issue by Streemo** [meteorhacks/flow-router#98]
Uncaught URIError: URI malformed page.js:367 decodeURLEncodedURIComponentpage.js:391 Contextpage.js:270 1.page.replacepage.js:170 1.page.startpage.js:104 pagerouter.js:268 Router.initialize_init.js:8 (anonymous function)startup_client.js:30 runStartupCallbacksstartup_client.js:32 ready

I noticed that going to http://localhost:1710/%%%%$#U@$(@*#$(#@$(@#*( resulted in this error and my 404 page not showing. I went here randomly to to test a catch-all; FlowRouter.notFound.

I tried to replace my FlowRouter.notFound with a FlowRouter catch all: '/(.*)' at the bottom of my route list.

Same thing happened. Wondering if this is something going on with FlowRouter or just my code. In iron-router, a catch all would catch everything (iirc).

thanks

**Comment by arunoda** [comment]
This is a bad URL and it always throws an error. We can't track it.
Even github is having for this.
Check by visiting this page: https://github.com/meteorhacks/flow-router/issues/%%%%$#U@$(@#$(#@$(@#

**Comment by arunoda** [comment]
We don't current have a way to track down route level issues like this. May be in the future. I'll close this for now.
